
# ARCH defines
ARCH=gnulinux
#ARCH_FAM=generic
ARCH_FAM=gnulinux

# CFG (y/n) macros
CFG= GNULINUX


# What buildable modules does this board have, 
# default or private
#MOD_AVAIL+=XCP COM PDUR IPDUM WDGM WDGIF DET DCM DEM CANTP J1939TP CANIF RTE FEE NVM ECUM_FIXED ECUM_FLEXIBLE MCU EA KERNEL RAMLOG IOHWAB RTE E2E BSWM MEMIF DLT FRIF
MOD_AVAIL+=XCP COM PDUR IPDUM WDGM WDGIF DET DCM DEM CANTP J1939TP CANIF RTE FEE NVM ECUM_FIXED ECUM_FLEXIBLE MCU EA RAMLOG IOHWAB RTE E2E BSWM MEMIF DLT FRIF SOAD DOIP

# Linux OS
MOD_AVAIL+=LINUXOS LINUXOS_DB

# Network management
MOD_AVAIL+=COMM NM CANNM CANSM NMHB UDPNM 
# Additional
MOD_AVAIL+=CRC CPL CAL
MOD_AVAIL+=LIN
MOD_AVAIL+=LINSM
MOD_AVAIL+=LINIF
MOD_AVAIL+=RAMTST
MOD_AVAIL+=CDDPDUR
MOD_AVAIL+=ETHSM
MOD_AVAIL+=FRSM
MOD_AVAIL+=FRNM
MOD_AVAIL+=FRTP
MOD_AVAIL+=ETHIF
MOD_AVAIL+=TCPIP
MOD_AVAIL+=CANTRCV

# Required modules
#MOD_USE += 

# Sqlite3 devel library needed for this.
#MOD_USE += LINUXOS_DB

SELECT_CLIB=CLIB_NATIVE
