/*
* Configuration of module: Rte (Rte.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*/

/* Rte.c */
#include "Os.h"
#include "Rte_Type.h"
#include "Rte_Data.h"
#include <string.h>
#include "Rte_Calculator_Internal.h"
#include "Rte_Tester_Internal.h"
#include "Rte_Logger_Internal.h"
#include "Rte_Logger2_Internal.h"
#include "Com.h"

Rte_DE_UInt8 Rte_Buf_Tester_prototype_Argumentsarg1_ibuffer;
Rte_DE_UInt8 Rte_Buf_Tester_prototype_Argumentsarg2_ibuffer;
Rte_DE_UInt32 Rte_Buf_Tester_prototype_FreqReqfreq_ibuffer;
Rte_DE_UInt32 Rte_Buf_Tester_prototype_FreqReqIndfreq_ibuffer;
Rte_DE_UInt16 Rte_Buf_Tester_prototype_Resultresult_ibuffer;
Rte_CDS_Tester Rte_Inst_Tester =
{
	.TesterRunnable_Arguments_arg1 = &Rte_Buf_Tester_prototype_Argumentsarg1_ibuffer,
	.TesterRunnable_Arguments_arg2 = &Rte_Buf_Tester_prototype_Argumentsarg2_ibuffer,
	.FreqReqRunnable_FreqReq_freq = &Rte_Buf_Tester_prototype_FreqReqfreq_ibuffer,
	.FreqReqRunnable_FreqReqInd_freq = &Rte_Buf_Tester_prototype_FreqReqIndfreq_ibuffer,
	.TesterRunnable_Result_result = &Rte_Buf_Tester_prototype_Resultresult_ibuffer,
};

Rte_DE_UInt16 Rte_Buf_Logger_prototype_Resultresult_ibuffer;
Rte_CDS_Logger Rte_Inst_Logger =
{
	.LoggerRunnable_Result_result = &Rte_Buf_Logger_prototype_Resultresult_ibuffer,
};

Rte_DE_UInt16 Rte_Buf_Logger2_prototype_Resultresult_ibuffer;
Rte_CDS_Logger2 Rte_Inst_Logger2 =
{
	.Logger2Runnable_Result_result = &Rte_Buf_Logger2_prototype_Resultresult_ibuffer,
};

void Rte_PRE_TesterRunnable() {
	imask_t irqMask = 0;
	Irq_Save(irqMask);

	uint8 Arg1_buf = 0;
	Com_ReceiveSignal(Arg1, &Arg1_buf);
	Rte_Inst_Tester.TesterRunnable_Arguments_arg1->value = (UInt8) Arg1_buf;

	uint8 Arg2_buf = 0;
	Com_ReceiveSignal(Arg2, &Arg2_buf);
	Rte_Inst_Tester.TesterRunnable_Arguments_arg2->value = (UInt8) Arg2_buf;

	Irq_Restore(irqMask);

}

void Rte_PRE_FreqReqRunnable() {
	imask_t irqMask = 0;
	Irq_Save(irqMask);

	uint32 FreqReqSig_buf = 0;
	Com_ReceiveSignal(FreqReqSig, &FreqReqSig_buf);
	Rte_Inst_Tester.FreqReqRunnable_FreqReq_freq->value
			= (UInt32) FreqReqSig_buf;

	Irq_Restore(irqMask);

}

void Rte_PRE_LoggerRunnable() {
	imask_t irqMask = 0;
	Irq_Save(irqMask);

	Rte_Inst_Logger.LoggerRunnable_Result_result->value
			= Rte_Buf_Tester_prototype_Result_result;

	Irq_Restore(irqMask);

}

void Rte_PRE_Logger2Runnable() {
	imask_t irqMask = 0;
	Irq_Save(irqMask);

	Rte_Inst_Logger2.Logger2Runnable_Result_result->value
			= Rte_Buf_Tester_prototype_Result_result;

	Irq_Restore(irqMask);

}

void Rte_POST_TesterRunnable() {
	imask_t irqMask = 0;
	Irq_Save(irqMask);

	uint8 ResultSig_buf =
			(uint8) Rte_Inst_Tester.TesterRunnable_Result_result->value;
	Com_SendSignal(ResultSig, &ResultSig_buf);

	Rte_WriteBuffer_Rte_Buf_Tester_prototype_Result_result(
			Rte_Inst_Tester.TesterRunnable_Result_result->value);

	Irq_Restore(irqMask);

}

void Rte_POST_FreqReqRunnable() {
	imask_t irqMask = 0;
	Irq_Save(irqMask);

	uint32 FreqIndSig_buf =
			(uint32) Rte_Inst_Tester.FreqReqRunnable_FreqReqInd_freq->value;
	Com_SendSignal(FreqIndSig, &FreqIndSig_buf);

	Irq_Restore(irqMask);

}

void Rte_TesterRunnable() {
	Rte_PRE_TesterRunnable();
	TesterRunnable();
	Rte_POST_TesterRunnable();
}

void Rte_FreqReqRunnable() {
	Rte_PRE_FreqReqRunnable();
	FreqReqRunnable();
	Rte_POST_FreqReqRunnable();
}

Std_ReturnType Rte_Multiply(const UInt8 arg1, const UInt8 arg2, UInt16* result) {
	Std_ReturnType retVal = Multiply(arg1, arg2, result);
	return retVal;
}

void Rte_LoggerRunnable() {
	Rte_PRE_LoggerRunnable();
	LoggerRunnable();
}

void Rte_Logger2Runnable() {
	Rte_PRE_Logger2Runnable();
	Logger2Runnable();
}

Std_ReturnType Rte_Start() {
	return RTE_E_OK;
}

void StepTask() {
	EventMaskType eventMask = 0;
	while (1) {
		WaitEvent( EVENT_MASK_StepEvent);
		GetResource( RES_SCHEDULER);
		GetEvent(TASK_ID_StepTask, &eventMask);
		ClearEvent(EVENT_MASK_StepEvent);
		ReleaseResource(RES_SCHEDULER);
		if (eventMask & EVENT_MASK_StepEvent) {
			Rte_TesterRunnable();
		}
		if (eventMask & EVENT_MASK_StepEvent) {
			Rte_Logger2Runnable();
		}
		if (eventMask & EVENT_MASK_StepEvent) {
			Rte_LoggerRunnable();
		}
	}
}

