/*
* Configuration of module: Rte (Rte_Cbk.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.13
*
* Generated by Arctic Studio (http://arccore.com) 
*/

/* Rte_Cbk.c */
#include "Os.h"
#include "Rte_Data.h"

void Rte_COMCbk_Arg1() {
}

void Rte_COMCbkTOut_Arg1() {
}

void Rte_COMCbk_Arg2() {
}

void Rte_COMCbkTOut_Arg2() {
}

void Rte_COMCbk_ResultSig() {
}

void Rte_COMCbkTOut_ResultSig() {
}

void Rte_COMCbk_FreqReqSig() {
	Rte_FreqReqRunnable();
}

void Rte_COMCbkTOut_FreqReqSig() {
}

void Rte_COMCbk_FreqIndSig() {
}

void Rte_COMCbkTOut_FreqIndSig() {
}

