/*
* Configuration of module: Rte (Rte_Logger2_Internal.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.13
*
* Generated by Arctic Studio (http://arccore.com) 
*/

/* Rte_Logger2.h */

#ifndef RTE_LOGGER2_H
#define RTE_LOGGER2_H

#include "Rte_Type.h"

UInt16 Rte_IRead_Logger2Runnable_Result_result();

void Logger2Runnable();

#endif
