/*
* Configuration of module: Rte (Rte_Cbk.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Wed Jun 15 15:06:41 CEST 2011
*/

/* Rte_Cbk.c */
#include "Os.h"
#include "Rte_Data.h"

void Rte_COMCbk_Arg1() {
}

void Rte_COMCbk_Arg2() {
}

void Rte_COMCbk_Result() {
}

