/*
* Configuration of module: Rte (Rte_Calculator.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jun 30 17:29:02 CEST 2011
*/

/* Rte_Calculator.c */
#include <string.h>
#include "Os.h"
#include "Rte_Calculator.h"
#include "Rte_Data.h"
#include "Com.h"

extern Rte_CDS_Calculator Rte_Inst_Calculator;

