/*
* Configuration of module: Rte (Rte_Logger.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jun 30 17:29:02 CEST 2011
*/

/* Rte_Logger.c */
#include <string.h>
#include "Os.h"
#include "Rte_Logger.h"
#include "Rte_Data.h"
#include "Com.h"

extern Rte_CDS_Logger Rte_Inst_Logger;

UInt16 Rte_IRead_LoggerRunnable_Result_result() {
	return Rte_Inst_Logger.LoggerRunnable_Result_result->value;
}

