/*
* Configuration of module: Rte (Rte_Calculator.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TMS570
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jun 30 17:29:02 CEST 2011
*/

/* Rte_Calculator.h */

#ifndef RTE_CALCULATOR_H
#define RTE_CALCULATOR_H

#include "Rte_Types.h"

Std_ReturnType Multiply(const UInt8 arg1, const UInt8 arg2, UInt16* result);

#endif
