/*
* Configuration of module: Pwm (Pwm_Cfg.c)
*
* Created by:              ArcCore AB
* Copyright:               Copyright ArcCore AB 2010
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       2.0.1
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Mar 10 10:49:01 CET 2011
*/

/*
 * Pwm_Cfg.c
 *
 *  Created on: 
 *      Author: 
 */

#include "Pwm.h"
#include "Pwm_Cfg.h"


/*
 * Notification routines are defined elsewhere but need to be linked from here,
 * so we define the routines as external here.
 */
extern void MyPwmNotificationRoutine(void); // PWM_CHANNEL_1

const Pwm_ConfigType PwmConfig = {
	.Channels = {
	
		PWM_CHANNEL_CONFIG(// Channel name and emios channel id
		                   PWM_CHANNEL_1,
		                   // Period in ticks
		                   4000,
		                   // Duty cycle (0 ~> 0%, 0x8000 ~> 100%)
		                   24576,
		                   // Local prescaler
		                   PWM_CHANNEL_PRESCALER_1,
		                   // Polarity
		                   PWM_HIGH),
		PWM_CHANNEL_CONFIG(// Channel name and emios channel id
		                   PWM_CHANNEL_2,
		                   // Period in ticks
		                   12000,
		                   // Duty cycle (0 ~> 0%, 0x8000 ~> 100%)
		                   0,
		                   // Local prescaler
		                   PWM_CHANNEL_PRESCALER_1,
		                   // Polarity
		                   PWM_LOW),
	},
#if PWM_NOTIFICATION_SUPPORTED==ON
	.NotificationHandlers = {
// Notification routine for PWM_CHANNEL_1
		MyPwmNotificationRoutine,							
// Notification routine for PWM_CHANNEL_2
		NULL,							
	}
#endif
};
