

EXAMPLENAME=schedule_table
ROOTDIR?=../../../..
include $(ROOTDIR)/examples/build_example.mk

ifneq (${MAKELEVEL},0) 

# object files
obj-y += schedule_table.o
obj-y += system_hooks.o

endif





