/* 
* Configuration of module Os (Os_Cfg.h)
* 
* Created by: 
* Configured for (MCU): MPC551x
* 
* Module editor vendor:  ArcCore
* Module editor version: 2.0.7
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Tue Jun 08 08:30:59 CEST 2010
*/


#if (OS_SW_MAJOR_VERSION != 2) 
#error "Os: Configuration file version differs from BSW version."
#endif


#ifndef OS_CFG_H_
#define OS_CFG_H_


// Alarm Id's
#define ALARM_ID_c_soft_1_inc_counter_2	0
#define ALARM_ID_c_soft_1_setevent_etask_m	1
#define ALARM_ID_c_sys_1_setevent_etask_m	2
#define ALARM_ID_c_sys_activate_btask_h	3

// Counter Id's
#define COUNTER_ID_OsTick	0
#define COUNTER_ID_soft_1	1
#define COUNTER_ID_soft_2	2

// Counter macros
#define OSMAXALLOWEDVALUE_OsTick 65535
#define OSMAXALLOWEDVALUE_soft_1 65535
#define OSMAXALLOWEDVALUE_soft_2 65535


// Event masks
#define EVENT_MASK_kill	32768
#define EVENT_MASK_notif	1

// Isr Id's

// Resource Id's
#define RES_ID_int_1	0
#define RES_ID_std_prio_3	1
#define RES_ID_std_prio_4	2
#define RES_ID_std_prio_5	3

// Linked resource id's

// Resource masks
#define RES_MASK_int_1	(1 << 0)
#define RES_MASK_std_prio_3	(1 << 1)
#define RES_MASK_std_prio_4	(1 << 2)
#define RES_MASK_std_prio_5	(1 << 3)

// Task Id's
#define TASK_ID_OsIdle	0
#define TASK_ID_btask_sup_h	1
#define TASK_ID_btask_sup_l	2
#define TASK_ID_btask_sup_m	3
#define TASK_ID_etask_master	4
#define TASK_ID_etask_sup_h	5
#define TASK_ID_etask_sup_l	6
#define TASK_ID_etask_sup_m	7

// Task entry points
void OsIdle( void );
void btask_sup_h( void );
void btask_sup_l( void );
void btask_sup_m( void );
void etask_master( void );
void etask_sup_h( void );
void etask_sup_l( void );
void etask_sup_m( void );

// Schedule table id's
#define SCHTBL_ID_0  0
#define SCHTBL_ID_1  1

// Stack size
#define OS_INTERRUPT_STACK_SIZE	2048
#define OS_OSIDLE_STACK_SIZE 512

#define OS_ALARM_CNT			4 
#define OS_TASK_CNT				8
#define OS_SCHTBL_CNT			2
#define OS_COUNTER_CNT			3
#define OS_EVENTS_CNT			2
#define OS_ISRS_CNT				0
#define OS_RESOURCE_CNT			4
#define OS_LINKED_RESOURCE_CNT	0

#define CFG_OS_DEBUG				STD_ON

#define OS_SC1 						STD_ON     
#define OS_STACK_MONITORING			STD_ON
#define OS_STATUS_EXTENDED			STD_ON
#define OS_USE_GET_SERVICE_ID		STD_ON
#define OS_USE_PARAMETER_ACCESS		STD_ON
#define OS_RES_SCHEDULER			STD_ON

#endif /*OS_CFG_H_*/
