
.PHONY: build_doc

# This dir.
export ARC_DOC_ROOT=$(CURDIR)
# Root of the core directory
export ROOTDIR=$(CURDIR)/../.. 
export PYTHON_ROOT=/c/Python27


export MIKTEX_ROOT?=/d/tmp/miktex/texmfs/install/miktex/bin
export PATH:=$(PATH):$(MIKTEX_ROOT):$(PYTHON_ROOT)/Scripts


build_doc:
	./build_doc.sh
	

