/*
* Configuration of module: IoHwAb (IoHwAb_Cbk.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       2.0.1
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jul 14 11:22:51 CEST 2011
*/


#ifndef _IOHWAB_CBK_H_
#define _IOHWAB_CBK_H_

//void IoHwAb_Adc_Notification_<group>();


//void IoHwAb_Icu_Notification_<channel>();

//void IoHwAb_Gpt_Notification_<channel>();

#endif