/*
* Configuration of module: Rte (Rte.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jul 14 11:22:51 CEST 2011
*/

/* Rte.c */
#include "Os.h"
#include "Rte_Types.h"
#include "Rte_Data.h"
#include <string.h>
#include "Rte_Blinker.h"
#include "Rte_led_rte_ecuc_mpc5567_IoHwAbComponentType.h"

Rte_CDS_Blinker Rte_Inst_Blinker = { };

Rte_CDS_led_rte_ecuc_mpc5567_IoHwAbComponentType
		Rte_Inst_led_rte_ecuc_mpc5567_IoHwAbComponentType = { };

void Rte_BlinkerRunnable() {
	BlinkerRunnable();
}

Std_ReturnType Rte_IoHwAb_Write_RED_LED(const BooleanType Value) {
	Std_ReturnType retVal = IoHwAb_Write_RED_LED(Value);
	return retVal;
}

Std_ReturnType Rte_Start() {
	return RTE_E_OK;
}

void Scheduled() {
	EventMaskType eventMask = 0;
	while (1) {
		WaitEvent( EVENT_MASK_ScheduleEvent);
		GetResource( RES_SCHEDULER);
		GetEvent(TASK_ID_Scheduled, &eventMask);
		ClearEvent(EVENT_MASK_ScheduleEvent);
		ReleaseResource(RES_SCHEDULER);
		if (eventMask & EVENT_MASK_ScheduleEvent) {
			Rte_BlinkerRunnable();
		}
	}
}

