/*
* Configuration of module: Rte (Rte_EcuAbstraction.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.13
*
* Generated by Arctic Studio (http://arccore.com) 
*/

/* Rte_EcuAbstraction.c */
#include <string.h>
#include "Os.h"
#include "Rte_EcuAbstraction.h"
#include "Rte_Data.h"

