/*
* Configuration of module: Rte (Rte_led_rte_ecuc_mpc5567_IoHwAbComponentType.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jul 14 11:22:51 CEST 2011
*/

/* Rte_led_rte_ecuc_mpc5567_IoHwAbComponentType.h */

#ifndef RTE_LED_RTE_ECUC_MPC5567_IOHWABCOMPONENTTYPE_H
#define RTE_LED_RTE_ECUC_MPC5567_IOHWABCOMPONENTTYPE_H

#include "Rte_Type.h"

Std_ReturnType IoHwAb_Write_RED_LED(const BooleanType Value);

Std_ReturnType IoHwAb_Read_RED_LED(BooleanType* Value);

#endif
