/*
* Configuration of module: Rte (Rte_led_rte_ecuc_mpc5567_IoHwAbComponentType.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jul 14 11:22:51 CEST 2011
*/

/* Rte_led_rte_ecuc_mpc5567_IoHwAbComponentType.c */
#include <string.h>
#include "Os.h"
#include "Rte_led_rte_ecuc_mpc5567_IoHwAbComponentType.h"
#include "Rte_Data.h"

extern Rte_CDS_led_rte_ecuc_mpc5567_IoHwAbComponentType
		Rte_Inst_led_rte_ecuc_mpc5567_IoHwAbComponentType;

