/*
* Configuration of module: Rte (Rte_Types.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jul 14 11:22:51 CEST 2011
*/

/* Rte_Types.h */

#ifndef RTE_TYPES_H
#define RTE_TYPES_H

#include "Rte.h"

typedef void * Rte_Instance;

typedef boolean BooleanType;

typedef struct {
	BooleanType value;
} Rte_DE_BooleanType;

typedef struct {
} Rte_PDS_Blinker_DigitalInterface_P;
typedef struct {
} Rte_PDS_Blinker_DigitalInterface_R;

typedef struct {
} Rte_CDS_Blinker;

typedef struct {
} Rte_PDS_led_rte_ecuc_mpc5567_IoHwAbComponentType_DigitalInterface_P;
typedef struct {
} Rte_PDS_led_rte_ecuc_mpc5567_IoHwAbComponentType_DigitalInterface_R;

typedef struct {
} Rte_CDS_led_rte_ecuc_mpc5567_IoHwAbComponentType;

#endif
