/*
* Configuration of module: Rte (Rte_Data.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jul 14 11:22:51 CEST 2011
*/

/* Rte_Data.h */

#ifndef RTE_DATA_H
#define RTE_DATA_H

#include "Rte_Types.h"
#include "cirq_buffer.h"

void Rte_BlinkerRunnable();

Std_ReturnType Rte_IoHwAb_Write_RED_LED(const BooleanType Value);

#endif
