/*
 * Configuration of module Mcu (Mcu_Cfg.c)
 *
 * Created by: 
 * Configured for (MCU): MPC5567
 *
 * Module vendor: ArcCore
 * Module version: 2.0.2
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Wed Jan 26 14:18:05 CET 2011
 */


#ifndef MCU_CFG_C_
#define MCU_CFG_C_

#include "Mcu.h"

Mcu_RamSectorSettingConfigType Mcu_RamSectorSettingConfigData[] = {
  {
  	.McuRamDefaultValue = 0,
    .McuRamSectionBaseAddress = 0,
  	.McuRamSectionSize = 0xFF,
  }
};

Mcu_ClockSettingConfigType Mcu_ClockSettingConfigData[] =
{
  {
    .McuClockReferencePointFrequency = 16000000UL,
    .Pll1    = 2,
    .Pll2    = 11,
    .Pll3    = 0,
  },
};


const Mcu_ConfigType McuConfigData[] = {
  {
	.McuClockSrcFailureNotification = 0,
	.McuRamSectors = 1,
	.McuClockSettings = 1,
	.McuDefaultClockSettings = 0,
	.McuClockSettingConfig = &Mcu_ClockSettingConfigData[0],
	.McuRamSectorSettingConfig = &Mcu_RamSectorSettingConfigData[0],
  }
};

#endif /*MCU_CFG_C_*/
