/*
* Configuration of module: Adc (Adc_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       2.0.0
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Fri Jun 17 23:12:13 CEST 2011
*/


#include "Adc.h"

Adc_GroupStatus AdcGroupStatus[ADC_NBR_OF_GROUPS];
	

const Adc_HWConfigurationType AdcHWUnitConfiguration[] =
{
	{
		.convTime = ADC_CONVERSION_TIME_8_CLOCKS,
		.resolution = ADC_RESOLUTION_8_BIT,
		.adcPrescale = ADC_SYSTEM_CLOCK_DIVIDE_FACTOR_6,
	},
};

const Adc_ChannelConfigurationType AdcChannelConfiguration [ADC_NBR_OF_CHANNELS] =
{
	{ .adcChannelConvTime = ADC_SampleTime_0 },
};
const Adc_ChannelType Adc_ADCGroup1ChannelList[ADC_NBR_OF_ADCGROUP1_CHANNELS] =
{	
	ADC_CH2,
};

Adc_ValueGroupType Adc_ADCGroup1Buffer [sizeof(Adc_ADCGroup1ChannelList)/sizeof(Adc_ADCGroup1ChannelList[0])];

const Adc_GroupDefType AdcGroupConfiguration [] =
{
	{
		.conversionMode 	= ADC_CONV_MODE_CONTINUOUS,
		.triggerSrc 		= ADC_TRIGG_SRC_SW,
		.groupCallback 		= NULL,
		.channelList 		= Adc_ADCGroup1ChannelList,
		.resultBuffer       = Adc_ADCGroup1Buffer,		
		.numberOfChannels   = sizeof(Adc_ADCGroup1ChannelList)/sizeof(Adc_ADCGroup1ChannelList[0]),
		.status             = &AdcGroupStatus[0],		
	},
};

const Adc_ConfigType AdcConfig[] =
{
  {
   .hwConfigPtr      = AdcHWUnitConfiguration,
   .groupConfigPtr   = AdcGroupConfiguration,
  }
};

