/*
* Configuration of module: Dio (Dio_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       2.0.0
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((DIO_SW_MAJOR_VERSION == 1) && (DIO_SW_MINOR_VERSION == 0)) )
#error Dio: Configuration file expected BSW module version to be 1.0.*
#endif


#ifndef DIO_CFG_H_
#define DIO_CFG_H_

#define DIO_VERSION_INFO_API    STD_OFF
#define DIO_DEV_ERROR_DETECT    STD_OFF

#define DIO_END_OF_LIST  (-1u)

// Physical ports
typedef enum
{
  DIO_PORT_A = 0,
  DIO_PORT_E = 1,
  DIO_PORT_B = 2,
  DIO_PORT_H = 3,
  DIO_PORT_J = 4,
  DIO_PORT_K = 5,
  DIO_PORT_M = 6,
  DIO_PORT_P = 7,
  DIO_PORT_S = 8,
  DIO_PORT_T = 9,
} Dio_PortTypesType;


// Channels	
#define DIO_CHANNEL_NAME_DI_PH0	24
#define DIO_CHANNEL_NAME_DI_PH1	25
#define DIO_CHANNEL_NAME_DI_PH2	26
#define DIO_CHANNEL_NAME_DI_PH3	27
#define DIO_CHANNEL_NAME_DI_PH4	28
#define DIO_CHANNEL_NAME_DI_PH5	29
#define DIO_CHANNEL_NAME_DI_PH6	30
#define DIO_CHANNEL_NAME_DI_PH7	31
#define DIO_CHANNEL_NAME_DO_PB0	16
#define DIO_CHANNEL_NAME_DO_PB1	17
#define DIO_CHANNEL_NAME_DO_PB2	18
#define DIO_CHANNEL_NAME_DO_PB3	19
#define DIO_CHANNEL_NAME_DO_PB4	20
#define DIO_CHANNEL_NAME_DO_PB5	21
#define DIO_CHANNEL_NAME_DO_PB6	22
#define DIO_CHANNEL_NAME_DO_PB7	23
#define DIO_CHANNEL_NAME_DI_PT0	72
#define DIO_CHANNEL_NAME_DI_PT1	73
#define DIO_CHANNEL_NAME_DO_PT2	74
#define DIO_CHANNEL_NAME_RedLED	56

// Channel group
#define DIO_GROUP_NAME_DI_DIP	(&DioConfigData[0])
#define DIO_GROUP_NAME_DO_LEDBAR	(&DioConfigData[1])

// Ports
#define DIO_PORT_NAME_DipSwitch 		(DIO_PORT_H)
#define DIO_PORT_NAME_LEDBar 		(DIO_PORT_B)
#define DIO_PORT_NAME_Timer 		(DIO_PORT_T)
#define DIO_PORT_NAME_PWMPort 		(DIO_PORT_P)




// Pointers for convenience.
// Channels	
extern const Dio_ChannelType DioChannelConfigData[];
// Channel group
extern const Dio_ChannelGroupType DioConfigData[];
// Port
extern const Dio_PortType DioPortConfigData[];

#endif /*DIO_CFG_H_*/
