/*
 * Configuration of module Gpt (Gpt_Cfg.c)
 *
 * Created by: 
 * Configured for (MCU): HCS12
 *
 * Module vendor: ArcCore
 * Module version: 2.0.1
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Mon Nov 08 20:30:03 CET 2010
 */

#warning "This default file may only be used as an example!"

#include "Gpt.h"
#include "Gpt_Cfg.h"
#include <stdlib.h>

const Gpt_ConfigType GptConfigData[] =
{
  {
	.GptChannelId = GPT_CHANNEL_ILL,
  }
};
