/*
 * Configuration of module Gpt (Gpt_Cfg.h)
 *
 * Created by: 
 * Configured for (MCU): HCS12
 *
 * Module vendor: ArcCore
 * Module version: 2.0.1
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Mon Nov 08 20:30:03 CET 2010
 */


#if (GPT_SW_MAJOR_VERSION != 1) 
#error "Gpt: Configuration file version differs from BSW version."
#endif

#ifndef GPT_CFG_H_
#define GPT_CFG_H_

#warning "This default file may only be used as an example!"

#include "Std_Types.h"


#define GPT_VARIANT_PC	STD_OFF
#define GPT_VARIANT_PB	STD_ON

/** HW PIT channels */
#define GPT_CHANNEL_RTI	0
#define GPT_CHANNEL_0	0
#define GPT_CHANNEL_1	1
#define GPT_CHANNEL_2	2
#define GPT_CHANNEL_3	3
#define GPT_CHANNEL_4	4
#define GPT_CHANNEL_5	5
#define GPT_CHANNEL_6	6
#define GPT_CHANNEL_7	7

#define GPT_CHANNEL_CNT	8

#if defined(CFG_MPC55XX)
#define GPT_CHANNEL_DEC	9
#endif

// Illegal channel
#define GPT_CHANNEL_ILL	31


#define GPT_DEV_ERROR_DETECT					STD_OFF
#define GPT_REPORT_WAKEUP_SOURCE				STD_OFF
#define GPT_DEINIT_API  						STD_OFF
#define GPT_ENABLE_DISABLE_NOTIFICATION_API     STD_OFF
#define GPT_TIME_REMAINING_API					STD_OFF
#define GPT_TIME_ELAPSED_API                    STD_OFF
#define GPT_VERSION_INFO_API					STD_OFF
#define GPT_WAKEUP_FUNCTIONALITY_API			STD_OFF


typedef struct  {
	uint32 GptChannelClkSrc;
	Gpt_ChannelType GptChannelId;
	Gpt_ChannelMode GptChannelMode;
	void (*GptNotification)();
	uint32 GptChannelPrescale;
	boolean GptEnableWakeup;
} Gpt_ConfigType;

extern const Gpt_ConfigType GptConfigData[];

#endif /*GPT_CFG_H_*/
