/*
 * Configuration of module Pwm (Pwm_Cfg.c)
 *
 * Created by: 
 * Configured for (MCU): HCS12
 *
 * Module vendor: ArcCore
 * Module version: 2.0.1
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Mon Nov 08 20:30:03 CET 2010
 */


#include "Pwm.h"
#include "Pwm_Cfg.h"


const Pwm_ConfigType PwmConfig =
{
		.channels = { 		
			{
				.channel =  GREENLED,
				DUTY_AND_PERIOD(10,10),
				.centerAlign =  STD_OFF,
				.polarity = POLARITY_NORMAL,
				.scaledClockEnable = STD_ON,
			}, 		
			{
				.channel =  REDLED,
				DUTY_AND_PERIOD(10,10),
				.centerAlign =  STD_OFF,
				.polarity = POLARITY_NORMAL,
				.scaledClockEnable = STD_ON,
			},
		},
		.busPrescalerA = PRESCALER_2,
		.busPrescalerB = PRESCALER_2,
		.PrescalerA = 1,
		.PrescalerB = 1,
};
