
SPHINXDIR=../../../../scripts/sphinx

doc_module=OSAL
doc_type=dd
doc_mcu=mpc560x

#rstp-y += index.rst

#build_mcal_doc can um mpc5xxx
#build_mcal_dd_doc MCAL dd

include $(SPHINXDIR)/build_doc.mk








