

# Memory 
MOD_AVAIL+=NVM MEMIF FEE FLS EEP EA
# System + Communication + Diagnostic

MOD_AVAIL+=XCP CANIF CANTP FRTP LINTP LINIF COM DCM DEM FIM DET DLT STBM ECUM_FIXED SAFEIOHWAB IOHWAB KERNEL PDUR WDGM WDGIF ETHIF FRIF SOAD SD QUEUE SAFEQ

MOD_AVAIL+=RTE J1939TP SCHM ECUM_FLEXIBLE BSWM ETHTSYN SOMEIPXF E2EXF
# Network management

MOD_AVAIL+=COMM NM CANNM CANSM LINSM FRSM FRNM IPDUM ETHSM SECOC

# Additional
MOD_AVAIL+= RAMLOG CRC CDDPDUR CPL CAL RAMTST DLTUARTCOM LDCOM FRTP CDDETHTRCV E2E OSEKNM HTMSS RTM SMAL

#Transceivers
MOD_AVAIL+= CDDETHTRCV CANTRCV


