

# Memory 
MOD_AVAIL+=NVM MEMIF FEE FLS EEP EA
# System + Communication + Diagnostic

MOD_AVAIL+=XCP CANIF CANTP FRTP LINTP LINIF COM DCM DEM FIM DET DLT STBM ECUM_FIXED SAFEIOHWAB IOHWAB KERNEL PDUR WDGM WDGIF ETHIF FRIF SOAD DOIP SD QUEUE SAFEQ

MOD_AVAIL+=RTE J1939TP SCHM ECUM_FLEXIBLE BSWM ETHTSYN SOMEIPXF E2EXF
# Network management

MOD_AVAIL+=COMM NM CANNM CANSM LINSM FRSM FRNM IPDUM ETHSM SECOC

# Additional
MOD_AVAIL+= RAMLOG CRC CDDPDUR CPL CAL RAMTST DLTUARTCOM LDCOM FRTP CDDETHTRCV E2E OSEKNM HTMSS RTM SMAL

#Transceivers
MOD_AVAIL+= CDDETHTRCV CANTRCV

ifneq ($(SELECT_COV_TOOL),)
  CFG+=FILE_MEM_PARTITION
  CFG+=FS_RAM
  ifeq ($(SELECT_COV_TOOL),gcov)
    CFG+=GCOV
  endif
  ifeq ($(SELECT_COV_TOOL),bullseye)
    CFG+=BULLSEYE
  endif
endif

COV_BULLSEYE_PATH?=/c/devtools/BullseyeCoverage
# We require at least this version...
COV_BULLSEYE_REQ_VERSION?=81411

ifneq ($(SELECT_TEST_OUTPUT),)
  ifeq ($(SELECT_TEST_OUTPUT),xml)
    def-y+= XML_OUTPUTTER_SKIP_HEADER
	def-y+= XML_OUTPUTTER_HTML_ESCAPE
	def-y+= EMBUNIT_XML_OUTPUT
  endif
endif




