/*
* Configuration of module: Port (Port_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       2.0.2
*
* Generated by Arctic Studio (http://arccore.com) 
*/

	


#include "Port.h"

#define PORT_UNDEFINED 0x00

const Port_ConfigType PortConfigData =
{
    .corePullUpRegister = 0x90,
    .coreReducedDriveRegister = 0x00,
    .modeRoutingRegister = 0x00,

      #if ( PORTA_CONFIGURABLE == STD_ON )
    .portADirection = PORT_UNDEFINED,
    .portAOutValue = PORT_UNDEFINED,
    .portAMask = PORT_UNDEFINED,
      #endif

      #if ( PORTB_CONFIGURABLE == STD_ON )
    .portBDirection = PORT_UNDEFINED,
    .portBOutValue = PORT_UNDEFINED,
    .portBMask = PORT_UNDEFINED,
      #endif

      #if ( PORTE_CONFIGURABLE == STD_ON )
    .portEDirection = PORT_UNDEFINED,
    .portEOutValue = PORT_UNDEFINED,
    .portEMask = PORT_UNDEFINED,
      #endif

      #if ( PORTK_CONFIGURABLE == STD_ON )
    .portKDirection = PORT_UNDEFINED,
    .portKOutValue = PORT_UNDEFINED,
    .portKMask = PORT_UNDEFINED,
      #endif

      #if ( PORTH_CONFIGURABLE == STD_ON )
    .portHDirection = 0x80,
    .portHOutValue = 0x0,
    .portHMask = 0x0,
    .portHPullEnableRegister = 0x0,
    .portHPullPolarityRegsiter = 0x0,
    .portHReducedDriveRegister = 0x0,
      #endif

      #if ( PORTJ_CONFIGURABLE == STD_ON )
    .portJDirection = PORT_UNDEFINED,
    .portJOutValue = PORT_UNDEFINED,
    .portJMask = PORT_UNDEFINED,
    .portJPullEnableRegister = PORT_UNDEFINED,
    .portJPullPolarityRegsiter = PORT_UNDEFINED,
    .portJReducedDriveRegister = PORT_UNDEFINED,
      #endif

      #if ( PORTM_CONFIGURABLE == STD_ON )
    .portMDirection = PORT_UNDEFINED,
    .portMOutValue = PORT_UNDEFINED,
    .portMMask = PORT_UNDEFINED,
    .portMPullEnableRegister = PORT_UNDEFINED,
    .portMPullPolarityRegsiter = PORT_UNDEFINED,
    .portMWiredModeRegsiter = PORT_UNDEFINED,
    .portMReducedDriveRegister = PORT_UNDEFINED,
      #endif

      #if ( PORTP_CONFIGURABLE == STD_ON )
    .portPDirection = PORT_UNDEFINED,
    .portPOutValue = PORT_UNDEFINED,
    .portPMask = PORT_UNDEFINED,
    .portPPullEnableRegister = PORT_UNDEFINED,
    .portPPullPolarityRegsiter = PORT_UNDEFINED,
    .portPReducedDriveRegister = PORT_UNDEFINED,
      #endif

      #if ( PORTS_CONFIGURABLE == STD_ON )
    .portSDirection = PORT_UNDEFINED,
    .portSOutValue = PORT_UNDEFINED,
    .portSMask = PORT_UNDEFINED,
    .portSPullEnableRegister = PORT_UNDEFINED,
    .portSPullPolarityRegsiter = PORT_UNDEFINED,
    .portSWiredModeRegsiter = PORT_UNDEFINED,
    .portSReducedDriveRegister = PORT_UNDEFINED,
      #endif

      #if ( PORTT_CONFIGURABLE == STD_ON )
    .portTDirection = PORT_UNDEFINED,
    .portTOutValue = PORT_UNDEFINED,
    .portTMask = PORT_UNDEFINED,
    .portTPullEnableRegister = PORT_UNDEFINED,
    .portTPullPolarityRegsiter = PORT_UNDEFINED,
    .portTReducedDriveRegister = PORT_UNDEFINED,
      #endif
};


