/* 
* Configuration of module EcuC (ComGlobals.h)
* 
* Created by: 
* Configured for (MCU): MPC5567
* 
* Module vendor:  ArcCore
* Module version: 2.0.0
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Thu Jun 17 15:44:15 CEST 2010
*/


#if (ECUC_SW_MAJOR_VERSION != 1) 
#error "EcuC: Configuration file version differs from BSW version."
#endif


#ifndef COMGLOBALS_H_
#define COMGLOBALS_H_

// PDU handle id definitions.
enum {
	LedCommandTx = 0,
};

#endif
