/*
* Configuration of module: PduR (PduR_PbCfg.h)
*
* Created by:              Arccore AB
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       2.0.2
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Mar 10 10:50:24 CET 2011
*/


#if !(((PDUR_SW_MAJOR_VERSION == 1) && (PDUR_SW_MINOR_VERSION == 0)) )
#error PduR: Configuration file expected BSW module version to be 1.0.*
#endif


#if defined(USE_DCM)
#include "Dcm.h"
#endif
#if defined(USE_COM)
#include "Com.h"
#endif
#if defined(USE_CANIF)
#include "CanIf.h"
#endif
#if defined(USE_CANTP)
#include "CanTp.h"
#endif

extern PduR_PBConfigType PduR_Config;

//  PduR Polite Defines.

#define PDUR_SOURCE_PDU_ID_LedCommandTx COM_PDU_ID_LedCommandTx
#define PDUR_DEST_PDU_ID_LedCommandTx CANIF_PDU_ID_LedCommandTx
