
# ARCH defines
ARCH=linux
ARCH_FAM=generic

# CFG (y/n) macros
CFG+=BRD_LINUX
CFG+=SYSTEM_ASSERT

# What buildable modules does this board have, 
# default or private
MOD_AVAIL+=XCP COM PDUR IPDUM WDGM WDGIF DET DCM DEM CANTP J1939TP CANIF RTE FEE NVM ECUM_FIXED ECUM_FLEXIBLE MCU EA KERNEL RAMLOG IOHWAB RTE E2E BSWM MEMIF DLT FRIF TCPIP LWIP 

# Network management
MOD_AVAIL+=COMM NM CANNM CANSM NMHB UDPNM
# Additional
MOD_AVAIL+=CRC CPL CAL
MOD_AVAIL+=LIN
MOD_AVAIL+=LINSM
MOD_AVAIL+=LINIF
MOD_AVAIL+=RAMTST
MOD_AVAIL+=CANTRCV
MOD_AVAIL+=CDDPDUR
MOD_AVAIL+=ETHSM
MOD_AVAIL+=FRSM
MOD_AVAIL+=FRNM
MOD_AVAIL+=FRTP
MOD_AVAIL+=ETHIF
MOD_AVAIL+=ETHTSYN
MOD_AVAIL+=LDCOM
MOD_AVAIL+=STBM
# Required modules
#MOD_USE += 

# Needed by us
MOD_USE=
SELECT_CLIB=CLIB_NATIVE
