/*
* Configuration of module: Os (Tasks.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.34
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Tue Jul 05 15:02:10 CEST 2011
*/

#include "Os.h"
#include "EcuM.h"
#include "Com.h"
#include "CanIf.h"

// #define USE_LDEBUG_PRINTF // Uncomment this to turn debug statements on.
#include "debug.h"


// Tasks
void Task1( void ) {

	EcuM_StartupTwo();

	CanIf_SetControllerMode(CANIF_Controller_A, CANIF_CS_STARTED);
	Com_IpduGroupStart(CanDbImportedPdus, 1);

	TerminateTask();
}

uint32 CanDB_Signal_32_21_BE_buffer;
uint8  CanDB_Signal_1_4_LE_buffer;
sint16 CanDB_Signal_45_12_LE_buffer;
sint16 CanDB_Signal_29_12_BE_buffer;

void Task2( void ) {

	Com_MainFunctionRx();

	Com_ReceiveSignal(CanDB_Signal_32_21_BE_Tester, &CanDB_Signal_32_21_BE_buffer);
	Com_ReceiveSignal(CanDB_Signal_1_4_LE_Tester,   &CanDB_Signal_1_4_LE_buffer);
	Com_ReceiveSignal(CanDB_Signal_45_12_LE_Tester, &CanDB_Signal_45_12_LE_buffer);
	Com_ReceiveSignal(CanDB_Signal_29_12_BE_Tester, &CanDB_Signal_29_12_BE_buffer);

	Com_SendSignal(CanDB_Signal_32_21_BE, &CanDB_Signal_32_21_BE_buffer);
	Com_SendSignal(CanDB_Signal_1_4_LE,   &CanDB_Signal_1_4_LE_buffer);
	Com_SendSignal(CanDB_Signal_45_12_LE, &CanDB_Signal_45_12_LE_buffer);
	Com_SendSignal(CanDB_Signal_29_12_BE, &CanDB_Signal_29_12_BE_buffer);

	Com_MainFunctionTx();

	TerminateTask();
}


void OsIdle( void ) {
	while(1);
}


// Hooks
#define ERROR_LOG_SIZE 20

struct LogBad_s {
	uint32_t param1;
	uint32_t param2;
	uint32_t param3;
	TaskType taskId;
	OsServiceIdType serviceId;
	StatusType error;
};

void ErrorHook ( StatusType Error ) {

	TaskType task;
	static struct LogBad_s LogBad[ERROR_LOG_SIZE];
	static uint8_t ErrorCount = 0;
	GetTaskID(&task);
	OsServiceIdType service = OSErrorGetServiceId();
	
	LDEBUG_PRINTF("## ErrorHook err=%d\n",Error);

	/* Log the errors in a buffer for later review */
	LogBad[ErrorCount].param1 = os_error.param1;
	LogBad[ErrorCount].param2 = os_error.param2;
	LogBad[ErrorCount].param3 = os_error.param3;
	LogBad[ErrorCount].serviceId = service;
	LogBad[ErrorCount].taskId = task;
	LogBad[ErrorCount].error = Error;

	ErrorCount++;

	// Stall if buffer is full.
	while(ErrorCount >= ERROR_LOG_SIZE);

}

void PostTaskHook ( void ) {
	TaskType task;
	GetTaskID(&task);
	LDEBUG_PRINTF("## PreTaskHook, taskid=%d\n",task);
}

void PreTaskHook ( void ) {
	TaskType task;
	GetTaskID(&task);
	LDEBUG_PRINTF("## PreTaskHook, taskid=%d\n",task);
}

void ShutdownHook ( StatusType Error ) {
	LDEBUG_PRINTF("## ShutdownHook\n");
	while(1);
}

void StartupHook ( void ) {
	LDEBUG_PRINTF("## StartupHook\n");
}
