/* 
* Configuration of module Os (Os_Cfg.c)
* 
* Created by: 
* Configured for (MCU): Undefined MCU
* 
* Module vendor:  ArcCore
* Module version: 2.0.11
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Sun Oct 10 18:57:50 CEST 2010
*/

	

#include <stdlib.h>
#include <stdint.h>
#include "Platform_Types.h"
#include "Os.h"				// includes Os_Cfg.h
#include "os_config_macros.h"
#include "kernel.h"
#include "kernel_offset.h"
#include "alist_i.h"
#include "Mcu.h"

extern void dec_exception( void );

// Set the os tick frequency
OsTickType OsTickFreq = 1000;


// ###############################    DEBUG OUTPUT     #############################
uint32 os_dbg_mask = 0;
 


// #################################    COUNTERS     ###############################
GEN_COUNTER_HEAD {
	GEN_COUNTER(	COUNTER_ID_soft1,
					"soft1",
					COUNTER_TYPE_SOFT,
					COUNTER_UNIT_NANO,
					65535,
					1,
					2,
					0),
	GEN_COUNTER(	COUNTER_ID_system_tick,
					"system_tick",
					COUNTER_TYPE_HARD,
					COUNTER_UNIT_NANO,
					0xffff,
					1,
					1,
					0),
};

CounterType Os_Arc_OsTickCounter = COUNTER_ID_system_tick;

// ##################################    ALARMS     ################################

GEN_ALARM_HEAD {
	GEN_ALARM(	ALARM_ID_act_etask_h_full,
				"act_etask_h_full",
				COUNTER_ID_soft1,
				NULL,
				ALARM_ACTION_ACTIVATETASK,
				TASK_ID_etask_h_full,
				NULL,
				NULL ),
	GEN_ALARM(	ALARM_ID_act_etask_l_non,
				"act_etask_l_non",
				COUNTER_ID_soft1,
				NULL,
				ALARM_ACTION_ACTIVATETASK,
				TASK_ID_etask_l_non,
				NULL,
				NULL ),
	GEN_ALARM(	ALARM_ID_setev_go_etask_h_full,
				"setev_go_etask_h",
				COUNTER_ID_soft1,
				NULL,
				ALARM_ACTION_SETEVENT,
				TASK_ID_etask_h_full,
				EVENT_MASK_go,
				NULL ),
	GEN_ALARM(	ALARM_ID_sys_tick_act_etask_h_full,
				"sys_tick_act_eta",
				COUNTER_ID_system_tick,
				NULL,
				ALARM_ACTION_ACTIVATETASK,
				TASK_ID_etask_h_full,
				NULL,
				NULL ),
};

// ################################    RESOURCES     ###############################
GEN_RESOURCE_HEAD {
};

// ##############################    STACKS (TASKS)     ############################
DECLARE_STACK(OsIdle,OS_OSIDLE_STACK_SIZE);
DECLARE_STACK(etask_h_full,2048);
DECLARE_STACK(etask_l_non,2048);
DECLARE_STACK(etask_m_full,2048);

// ##################################    TASKS     #################################
GEN_TASK_HEAD {
	GEN_ETASK(	OsIdle,
				0,
				FULL,
				TRUE,
				NULL,
				0 
	),
	GEN_ETASK(
		etask_h_full,
		6,
		FULL,
		FALSE,
		NULL,
		0
	),
		
				
	GEN_ETASK(
		etask_l_non,
		4,
		NON,
		FALSE,
		NULL,
		0
	),
		
				
	GEN_ETASK(
		etask_m_full,
		5,
		FULL,
		TRUE,
		NULL,
		0
	),
		
				
};

// ##################################    HOOKS     #################################
GEN_HOOKS( 
	StartupHook, 
	NULL, 
	ShutdownHook, 
	ErrorHook,
	PreTaskHook, 
	PostTaskHook 
);

// ##################################    ISRS     ##################################


// ############################    SCHEDULE TABLES     #############################

// Table heads
GEN_SCHTBL_HEAD {
};

GEN_PCB_LIST()

uint8_t os_interrupt_stack[OS_INTERRUPT_STACK_SIZE] __attribute__ ((aligned (0x10)));

GEN_IRQ_VECTOR_TABLE_HEAD {};
GEN_IRQ_ISR_TYPE_TABLE_HEAD {};
GEN_IRQ_PRIORITY_TABLE_HEAD {};

#include "os_config_funcs.h"
