/*
 * Configuration of module Com (Com_PbCfg.c)
 *
 * Created by: ArcCore AB
 * Configured for (MCU): MPC551x
 *
 * Module vendor: ArcCore
 * Module version: 2.0.5
 *
 * Copyright ArcCore AB 2010
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Mon Jan 17 12:24:21 CET 2011
 */


#include "Com.h"
#include "Com_Internal.h"
#include <stdlib.h>
#if defined(USE_PDUR)
#include "PduR.h"
#endif





/*
 * Signal init values.
 */
const uint16 Com_SignalInitValue_SetLedLevelTx = 0;
	

/*
 * Group signal definitions
 */
const ComGroupSignal_type ComGroupSignal[] = {
	{
		.Com_Arc_EOL = 1
	}
};


/* SignalGroup GroupSignals lists. */

/*
 * Signal definitions
 */
const ComSignal_type ComSignal[] = {
	{
		.ComHandleId = SetLedLevelTx,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = &Com_SignalInitValue_SetLedLevelTx,
		.ComBitPosition = 7,
		.ComBitSize = 16,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT16,
		.Com_Arc_IsSignalGroup = 0,
		.ComGroupSignal = NULL,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.Com_Arc_EOL = 1
	}
};


/*
 * I-PDU group definitions
 */
const ComIPduGroup_type ComIPduGroup[] = {
	{
		.ComIPduGroupHandleId = TxGroup,
		.Com_Arc_EOL = 0
	},
	
	{
		.Com_Arc_EOL  = 1
	}
};

/* IPdu signal lists. */
const ComSignal_type * const ComIPduSignalRefs_LedCommandTx[] = {
	&ComSignal[ SetLedLevelTx ],		
	NULL,
};

/*
 * I-PDU definitions
 */
const ComIPdu_type ComIPdu[] = {	
    
	{ // LedCommandTx
		.ArcIPduOutgoingId = PDUR_DEST_PDU_ID_LedCommandTx,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = SEND,
		.ComIPduGroupRef = TxGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = DIRECT,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = ComIPduSignalRefs_LedCommandTx,
		.Com_Arc_EOL = 0
	},   
	{
		.Com_Arc_EOL = 1
	}
};

const Com_ConfigType ComConfiguration = {
	.ComConfigurationId = 1,
	.ComIPdu = ComIPdu,
	.ComIPduGroup = ComIPduGroup,
	.ComSignal = ComSignal,
	.ComGroupSignal = ComGroupSignal
};

/* IPdu buffers and signal group buffers */
uint8 ComArcIPduBuffer_LedCommandTx[8];
	   

Com_Arc_IPdu_type Com_Arc_IPdu[] = {
	{ // LedCommandTx
		.Com_Arc_TxIPduTimers = {
			.ComTxIPduNumberOfRepetitionsLeft = 0,
			.ComTxModeRepetitionPeriodTimer = 0,
			.ComTxIPduMinimumDelayTimer = 0,
			.ComTxModeTimePeriodTimer = 0
		},
		.ComIPduDataPtr = ComArcIPduBuffer_LedCommandTx,
		.Com_Arc_IpduStarted = 0	
	},
};

Com_Arc_Signal_type Com_Arc_Signal[] = {
	{ // SetLedLevelTx
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = NULL
		
	},
	
};

Com_Arc_GroupSignal_type Com_Arc_GroupSignal[COM_N_GROUP_SIGNALS];

uint8 outgoingSduPtr[8];

Com_Arc_Config_type Com_Arc_Config = {
	.ComIPdu = Com_Arc_IPdu,
	.ComSignal = Com_Arc_Signal,
	.ComGroupSignal = Com_Arc_GroupSignal,
	.OutgoingPdu = {
			.SduDataPtr = outgoingSduPtr,
			.SduLength = 0
		}
};

