/* 
* Configuration of module EcuC (ComGlobals.h)
* 
* Created by: ArcCore AB
* Configured for (MCU): MPC551x
* 
* Module editor vendor:  ArcCore
* Module editor version: 2.0.0
* 
* Copyright ArcCore AB 2010
* Generated by Arctic Studio (http://arccore.com)
*           on Fri Apr 30 15:54:06 CEST 2010
*/


#if (ECUC_SW_MAJOR_VERSION != 1) 
#error "EcuC: Configuration file version differs from BSW version."
#endif


#ifndef COMGLOBALS_H_
#define COMGLOBALS_H_

// PDU handle id definitions.
enum {
	LedCommandTx = 0,
};

#endif
