/*
* Configuration of module: IoHwAb (IoHwAb_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       3.1.3
*
* Generated by Arctic Studio (http://arccore.com) 
*/

#ifndef IOHWAB_CFG_H_
#define IOHWAB_CFG_H_

#if !(((IOHWAB_SW_MAJOR_VERSION == 1) && (IOHWAB_SW_MINOR_VERSION == 0)) )
#error IoHwAb: Configuration file expected BSW module version to be 1.0.*
#endif

#define IOHWAB_DEV_ERROR_DETECT		STD_ON


#endif /* IOHWAB_CFG_H_ */
