/*
* Configuration of module: Rte (Rte_Blinker.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       0.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Wed Jul 06 20:28:46 CEST 2011
*/

/* Rte_Blinker.h */

#ifndef RTE_BLINKER_H
#define RTE_BLINKER_H

#include "Rte_Types.h"

#define Rte_Call_LED_Port_Write Rte_Call_Blinker_LED_Port_Write

Std_ReturnType Rte_Call_Blinker_LED_Port_Write(const BooleanType Value);

void BlinkerRunnable();

#endif
