

EXAMPLENAME=simple
ROOTDIR?=../../../..
include $(ROOTDIR)/examples/build_example.mk

ifneq (${MAKELEVEL},0) 

# object files
obj-y += simple_main.o
obj-y += system_hooks.o

endif





