/*
 * Configuration of module Com (Com_PbCfg.h)
 *
 * Created by: Arccore AB
 * Configured for (MCU): MPC551x
 *
 * Module vendor: ArcCore
 * Module version: 2.0.5
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Mon Jan 17 11:45:30 CET 2011
 */


#if !(((COM_SW_MAJOR_VERSION == 1) && (COM_SW_MINOR_VERSION == 1)) )
#error "Com: Configuration file version differs from BSW version."
#endif

#ifndef COM_PBCFG_H
#define COM_PBCFG_H

#include "Com_Types.h"

extern const Com_ConfigType ComConfiguration;

//  COM Polite Defines.
#define COM_PDU_ID_LedCommandRx		0



// PDU group definitions
#define RxGroup 0


// Signal definitions
#define SetLedLevelRx 0




#endif /* COM_PBCFG_H */
