/*
* Configuration of module: Com (Com_PbCfg.c)
*
* Created by:              Arccore AB
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.5
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Mar 10 09:37:44 CET 2011
*/


#include "Com.h"
#include "Com_Internal.h"
#include <stdlib.h>
#if defined(USE_PDUR)
#include "PduR.h"
#endif





/*
 * Signal init values.
 */
const uint16 Com_SignalInitValue_SetLedLevelRx = 0;
	

/*
 * Group signal definitions
 */
const ComGroupSignal_type ComGroupSignal[] = {
	{
		.Com_Arc_EOL = 1
	}
};


/* SignalGroup GroupSignals lists. */

/*
 * Signal definitions
 */
const ComSignal_type ComSignal[] = {
	{
		.ComHandleId = SetLedLevelRx,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = &Com_SignalInitValue_SetLedLevelRx,
		.ComBitPosition = 7,
		.ComBitSize = 16,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT16,
		.Com_Arc_IsSignalGroup = 0,
		.ComGroupSignal = NULL,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.Com_Arc_EOL = 1
	}
};


/*
 * I-PDU group definitions
 */
const ComIPduGroup_type ComIPduGroup[] = {
	{
		.ComIPduGroupHandleId = RxGroup,
		.Com_Arc_EOL = 0
	},
	
	{
		.Com_Arc_EOL  = 1
	}
};

/* IPdu signal lists. */
const ComSignal_type * const ComIPduSignalRefs_LedCommandRx[] = {
	&ComSignal[ SetLedLevelRx ],		
	NULL,
};

/*
 * I-PDU definitions
 */
const ComIPdu_type ComIPdu[] = {	
    
	{ // LedCommandRx
		.ArcIPduOutgoingId = PDUR_SOURCE_PDU_ID_LedCommandRx,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = RECEIVE,
		.ComIPduGroupRef = RxGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = NONE,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = ComIPduSignalRefs_LedCommandRx,
		.Com_Arc_EOL = 0
	},   
	{
		.Com_Arc_EOL = 1
	}
};

const Com_ConfigType ComConfiguration = {
	.ComConfigurationId = 1,
	.ComIPdu = ComIPdu,
	.ComIPduGroup = ComIPduGroup,
	.ComSignal = ComSignal,
	.ComGroupSignal = ComGroupSignal
};

/* IPdu buffers and signal group buffers */
uint8 ComArcIPduBuffer_LedCommandRx[8];
	   

Com_Arc_IPdu_type Com_Arc_IPdu[] = {
	{ // LedCommandRx
		.Com_Arc_TxIPduTimers = {
			.ComTxIPduNumberOfRepetitionsLeft = 0,
			.ComTxModeRepetitionPeriodTimer = 0,
			.ComTxIPduMinimumDelayTimer = 0,
			.ComTxModeTimePeriodTimer = 0
		},
		.ComIPduDataPtr = ComArcIPduBuffer_LedCommandRx,
		.Com_Arc_IpduStarted = 0	
	},
};

Com_Arc_Signal_type Com_Arc_Signal[] = {
	{ // SetLedLevelRx
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = NULL
		
	},
	
};

Com_Arc_GroupSignal_type Com_Arc_GroupSignal[COM_N_GROUP_SIGNALS];

uint8 outgoingSduPtr[8];

Com_Arc_Config_type Com_Arc_Config = {
	.ComIPdu = Com_Arc_IPdu,
	.ComSignal = Com_Arc_Signal,
	.ComGroupSignal = Com_Arc_GroupSignal,
	.OutgoingPdu = {
			.SduDataPtr = outgoingSduPtr,
			.SduLength = 0
		}
};

