/*
* Configuration of module: Os (Tasks.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       2.0.34
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Tue Jun 14 20:14:11 CEST 2011
*/

#include "Os.h"
#include "Dio.h"
#include "Com.h"
#include "EcuM.h"

// #define USE_LDEBUG_PRINTF // Uncomment this to turn debug statements on.
#include "debug.h"

// Callback when the FreqReq signal has arrived on COM
void IncommingFreqReq(void)
{
	SetEvent(TASK_ID_ComReceiveTask, EVENT_MASK_FreqReciveEvent);
}

// Call second stage of startup.
void StartTask()
{
	EcuM_StartupTwo();

	Com_IpduGroupStart(ComPduGroup, false);
	CanIf_SetControllerMode(CANIF_CONTROLLER_ID_CAN0, CANIF_CS_STARTED);

	// Makes the inital value on the bus be correct
	SetEvent(TASK_ID_ComReceiveTask, EVENT_MASK_FreqReciveEvent);
    TerminateTask();
}

// Task that changes the frequency of the LED when a new
// request is recieved from COM
void ComReceiveTask( void )
{
	uint32 freqreq;

	for(;;)
	{
		WaitEvent(EVENT_MASK_FreqReciveEvent);
		ClearEvent(EVENT_MASK_FreqReciveEvent);

		Com_ReceiveSignal(FreqReqSig, &freqreq);

		CancelAlarm(ALARM_ID_MainAlarm);
		SetRelAlarm(ALARM_ID_MainAlarm, 1, freqreq);

		Com_SendSignal(FreqIndSig, &freqreq);
	}
}

// Task that toggles the LED
Dio_LevelType level = 1;
void BlinkerTask( void ) {
	level = !level;
	Dio_WriteChannel(DIO_CHANNEL_NAME_LED_CHANNEL, level);
	TerminateTask();
}

// Simple task that drives the COM stack.
void ComTask( void ) {
	Com_MainFunctionRx();
	Com_MainFunctionTx();

	TerminateTask();
}

void OsIdle( void ) {
	while(1);
}


// Hooks
#define ERROR_LOG_SIZE 20

struct LogBad_s {
	uint32_t param1;
	uint32_t param2;
	uint32_t param3;
	TaskType taskId;
	OsServiceIdType serviceId;
	StatusType error;
};

void ErrorHook ( StatusType Error ) {

	TaskType task;
	static struct LogBad_s LogBad[ERROR_LOG_SIZE];
	static uint8_t ErrorCount = 0;
	GetTaskID(&task);
	OsServiceIdType service = OSErrorGetServiceId();
	
	LDEBUG_PRINTF("## ErrorHook err=%d\n",Error);

	/* Log the errors in a buffer for later review */
	LogBad[ErrorCount].param1 = os_error.param1;
	LogBad[ErrorCount].param2 = os_error.param2;
	LogBad[ErrorCount].param3 = os_error.param3;
	LogBad[ErrorCount].serviceId = service;
	LogBad[ErrorCount].taskId = task;
	LogBad[ErrorCount].error = Error;

	ErrorCount++;

	// Stall if buffer is full.
	while(ErrorCount >= ERROR_LOG_SIZE);

}

