/*
* Configuration of module: Fee (Fee_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#include "Fee.h"
#include "NvM_Cbk.h"

const Fee_BlockConfigType BlockConfigList[] = {
	{
		.BlockNumber = 2,		
		.BlockSize = 22,
		.ImmediateData = FALSE,
		.NumberOfWriteCycles = 0
	},	
	{
		.BlockNumber = 4,		
		.BlockSize = 14,
		.ImmediateData = FALSE,
		.NumberOfWriteCycles = 0
	},	
	{
		.BlockNumber = 3,		
		.BlockSize = 22,
		.ImmediateData = FALSE,
		.NumberOfWriteCycles = 0
	},	
};
const Fee_ConfigType Fee_Config = {
		.General = {
		#if (FEE_USE_JOB_NOTIFICATIONS == STD_ON)
				.NvmJobEndCallbackNotificationCallback = NvM_JobEndNotification,
				.NvmJobErrorCallbackNotificationCallback = NvM_JobErrorNotification		
		#else
				.NvmJobEndCallbackNotificationCallback = NULL,
				.NvmJobErrorCallbackNotificationCallback = NULL
		#endif
		},
		.BlockConfig = BlockConfigList,
};
