/*
* Configuration of module: Fee (Fee_Memory_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*/

#define FEE_BANK1_OFFSET	32768
#define FEE_BANK1_LENGTH	16384
#define FEE_BANK2_OFFSET	49152
#define FEE_BANK2_LENGTH	16384
