/*
* Configuration of module: Fee (Fee_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.9
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((FEE_SW_MAJOR_VERSION == 1) && (FEE_SW_MINOR_VERSION == 0)) )
#error Fee: Configuration file expected BSW module version to be 1.0.*
#endif

	
#ifndef FEE_CFG_H_
#define FEE_CFG_H_

#include "MemIf_Types.h"
#include "Fee_ConfigTypes.h"

#define FEE_DEV_ERROR_DETECT			STD_OFF
#define FEE_VERSION_INFO_API    		STD_OFF
#define FEE_POLLING_MODE				STD_ON
#define FEE_USE_JOB_NOTIFICATIONS		STD_ON

#define FEE_INDEX						0
#define FEE_VIRTUAL_PAGE_SIZE		    16

#define FEE_NUM_OF_BLOCKS				3
#define FEE_MAX_NUM_SETS				2 // 2^NvmDatasetSelectionBits 
#endif /*FEE_CFG_H_*/
