/*
* Configuration of module: MemIf (MemIf_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.2
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((MEMIF_SW_MAJOR_VERSION == 1) && (MEMIF_SW_MINOR_VERSION == 0)) )
#error MemIf: Configuration file expected BSW module version to be 1.0.*
#endif

	
#ifndef MEMIF_CFG_H_
#define MEMIF_CFG_H_

#include "MemIf_Types.h"

#if defined(USE_FEE)
#include "Fee.h"
#endif

#if defined(USE_EA)
#include "Ea.h"
#endif


#define MEMIF_VERSION_INFO_API    		STD_OFF
#define MEMIF_DEV_ERROR_DETECT			STD_OFF										
#define MEMIF_NUMBER_OF_DEVICES			1 // not generated

#if (MEMIF_NUMBER_OF_DEVICES == 1)
#if defined(USE_FEE) && defined(USE_EA)
#error Only one of Fee oe EA can be used at a time.
#else
#if defined(USE_FEE)
#define MEMIF_DEVICE_TO_USE				FLS_DRIVER_INDEX // not generated
#endif
#if defined(USE_EA)
#define MEMIF_DEVICE_TO_USE				EEP_DRIVER_INDEX // not generated
#endif
#endif
#endif
#endif /*MEMIF_CFG_H_*/
