/*
* Configuration of module: NvM (NvM_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.5
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#include "NvM.h"

/* Ram block for Block_2_Native */
extern uint8 Block_2_RamBlock[];
/* InitBlockCallbackFunction block for Block_2_Native */
extern Std_ReturnType Block_2_InitCallback(void);

// Single block callbacks
extern Std_ReturnType Block_Dataset_SingleCallback(uint8 ServiceId, NvM_RequestResultType JobResult);


// Multi block callback
extern void MultiBlock_Callback(uint8 ServiceId, NvM_RequestResultType JobResult);

#ifdef CFG_NVM_USE_SERVICE_COMPONENT
Std_ReturnType Block_1_Dataset_JobFinished(UInt8 ServiceId, NvM_RequestResultType JobResult) {
	return Rte_Call_Block_1_Dataset_NvMNotifyJobFinished_JobFinished(ServiceId, JobResult);
}
Std_ReturnType Block_2_Native_JobFinished(UInt8 ServiceId, NvM_RequestResultType JobResult) {
	return Rte_Call_Block_2_Native_NvMNotifyJobFinished_JobFinished(ServiceId, JobResult);
}

Std_ReturnType Block_1_Dataset_InitBlock(UInt8 ServiceId, NvM_RequestResultType JobResult) {
	return Rte_Call_Block_1_Dataset_NvMNotifyInitBlock_InitBlock(ServiceId, JobResult);
}
Std_ReturnType Block_2_Native_InitBlock(UInt8 ServiceId, NvM_RequestResultType JobResult) {
	return Rte_Call_Block_2_Native_NvMNotifyInitBlock_InitBlock(ServiceId, JobResult);
}

const blockNotifyJobFinishedFunc_t blockNotifyJobFinished[2] = {
	Block_1_Dataset_JobFinished,
	Block_2_Native_JobFinished,
};

const blockNotifyInitBlockFunc_t blockNotifyInitBlock[2] = {
	Block_1_Dataset_InitBlock,
	Block_2_Native_InitBlock,
};
#endif

const NvM_BlockDescriptorType BlockDescriptorList[] = {
	{
		.NvramBlockIdentifier = 1,                  // This is the configuration ID block (do not change)
		.BlockManagementType = NVM_BLOCK_NATIVE,
		.BlockWriteProt = STD_OFF,
		.WriteBlockOnce = STD_OFF,
		.SelectBlockForReadall = STD_OFF,		
		.SingleBlockCallback = NULL,
		.NvBlockLength = 2,
		.RamBlockDataAddress = NULL,
		.NvBlockNum = 1,
		.NvramDeviceId = 0,
		.NvBlockBaseNumber = 0,
		.BlockUseCrc = FALSE,
		.CalcRamBlockCrc = FALSE,
		.BlockJobPriority = 0,
		.ResistantToChangesSw = FALSE,
		.BlockCRCType = NVM_CRC16,
		.RomBlockNum = 0,
		.RomBlockDataAdress = NULL,
		.InitBlockCallback = NULL,
	},
	{
		.NvramBlockIdentifier = 2,
		.BlockManagementType = NVM_BLOCK_DATASET,
		.BlockWriteProt = STD_OFF,
		.WriteBlockOnce = STD_OFF,		/* Value is not configurable */
		.SelectBlockForReadall = STD_OFF,
		.SingleBlockCallback = Block_Dataset_SingleCallback,
		.NvBlockLength = 20,
		.RamBlockDataAddress = NULL,
		.NvBlockNum = 2,
		.NvramDeviceId = 1, 			/* Value is not configurable */		
		.NvBlockBaseNumber = 2,
		.BlockUseCrc = true,
		.CalcRamBlockCrc = false,
		.BlockJobPriority = 0,			/* Value is not configurable */
		.ResistantToChangesSw = FALSE,	/* Value is not configurable */
		.BlockCRCType = NVM_CRC16,
		.RomBlockNum = 0,
		.RomBlockDataAdress = NULL,
		.InitBlockCallback = NULL,
	},
	{
		.NvramBlockIdentifier = 3,
		.BlockManagementType = NVM_BLOCK_NATIVE,
		.BlockWriteProt = STD_OFF,
		.WriteBlockOnce = STD_OFF,		/* Value is not configurable */
		.SelectBlockForReadall = STD_ON,
		.SingleBlockCallback = NULL,
		.NvBlockLength = 10,
		.RamBlockDataAddress = Block_2_RamBlock,
		.NvBlockNum = 1,
		.NvramDeviceId = 1, 			/* Value is not configurable */		
		.NvBlockBaseNumber = 4,
		.BlockUseCrc = true,
		.CalcRamBlockCrc = false,
		.BlockJobPriority = 0,			/* Value is not configurable */
		.ResistantToChangesSw = FALSE,	/* Value is not configurable */
		.BlockCRCType = NVM_CRC32,
		.RomBlockNum = 0,
		.RomBlockDataAdress = NULL,
		.InitBlockCallback = Block_2_InitCallback,
	},
};

const NvM_ConfigType NvM_Config = {
		.Common = {
				.MultiBlockCallback = MultiBlock_Callback,
		},
		.BlockDescriptor = BlockDescriptorList,		
};
