/*
* Configuration of module: NvM (NvM_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.5
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((NVM_SW_MAJOR_VERSION == 1) && (NVM_SW_MINOR_VERSION == 0)) )
#error NvM: Configuration file expected BSW module version to be 1.0.*
#endif

	
#ifndef NVM_CFG_H_
#define NVM_CFG_H_

#include "NvM_Types.h"
#include "NvM_ConfigTypes.h"

#define NVM_DEV_ERROR_DETECT			STD_OFF
#define NVM_VERSION_INFO_API    		STD_OFF
#define NVM_SET_RAM_BLOCK_STATUS_API	STD_ON

#define NVM_API_CONFIG_CLASS			NVM_API_CONFIG_CLASS_2	// Class 1-3
#define NVM_COMPILED_CONFIG_ID			0						// 0..65535
#define NVM_CRC_NUM_OF_BYTES			10						// 1..65535
#define NVM_DATASET_SELECTION_BITS		1						// 0..8
#define NVM_DRV_MODE_SWITCH				STD_OFF					// OFF = SLOW, ON = FAST
#define NVM_DYNAMIC_CONFIGURATION		STD_OFF					// OFF..ON
#define NVM_JOB_PRIORIZATION			STD_OFF					// OFF..ON
#define NVM_MAX_NUMBER_OF_WRITE_RETRIES	2						// 0..7
#define NVM_POLLING_MODE				STD_OFF /* Value is not configurable */
#define NVM_SIZE_IMMEDIATE_JOB_QUEUE	0						// 1..255
#define NVM_SIZE_STANDARD_JOB_QUEUE		4						// 1..255

#define NVM_Block_1_Dataset_HANDLE 2
#define NVM_Block_2_Native_HANDLE 3

#define NVM_MAX_BLOCK_LENGTH			20

#define NVM_NUM_OF_NVRAM_BLOCKS			3

#ifdef CFG_NVM_USE_SERVICE_COMPONENT
typedef Std_ReturnType (*blockNotifyJobFinishedFunc_t)(UInt8, NvM_RequestResultType);
typedef Std_ReturnType (*blockNotifyInitBlockFunc_t)(UInt8, NvM_RequestResultType);

extern const blockNotifyJobFinishedFunc_t blockNotifyJobFinished[];
extern const blockNotifyInitBlockFunc_t blockNotifyInitBlock[];
#endif

extern const NvM_ConfigType NvM_Config;

#endif /*NVM_CFG_H_*/
