/*
* Configuration of module: NvM (NvM_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.5
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#include "NvM.h"


// Single block callbacks


// Multi block callback
extern void TEST_MultiBlockCallback(uint8 ServiceId, NvM_RequestResultType JobResult);

#ifdef CFG_NVM_USE_SERVICE_COMPONENT
Std_ReturnType block_1_dataset_JobFinished(UInt8 ServiceId, NvM_RequestResultType JobResult) {
	return Rte_Call_block_1_dataset_NvMNotifyJobFinished_JobFinished(ServiceId, JobResult);
}

Std_ReturnType block_1_dataset_InitBlock(UInt8 ServiceId, NvM_RequestResultType JobResult) {
	return Rte_Call_block_1_dataset_NvMNotifyInitBlock_InitBlock(ServiceId, JobResult);
}

const blockNotifyJobFinishedFunc_t blockNotifyJobFinished[1] = {
	block_1_dataset_JobFinished,
};

const blockNotifyInitBlockFunc_t blockNotifyInitBlock[1] = {
	block_1_dataset_InitBlock,
};
#endif

const NvM_BlockDescriptorType BlockDescriptorList[] = {
	{
		.NvramBlockIdentifier = 1,                  // This is the configuration ID block (do not change)
		.BlockManagementType = NVM_BLOCK_NATIVE,
		.BlockWriteProt = STD_OFF,
		.WriteBlockOnce = STD_OFF,
		.SelectBlockForReadall = STD_OFF,		
		.SingleBlockCallback = NULL,
		.NvBlockLength = 2,
		.RamBlockDataAddress = NULL,
		.NvBlockNum = 1,
		.NvramDeviceId = 0,
		.NvBlockBaseNumber = 0,
		.BlockUseCrc = FALSE,
		.CalcRamBlockCrc = FALSE,
		.BlockJobPriority = 0,
		.ResistantToChangesSw = FALSE,
		.BlockCRCType = NVM_CRC16,
		.RomBlockNum = 0,
		.RomBlockDataAdress = NULL,
		.InitBlockCallback = NULL,
	},
	{
		.NvramBlockIdentifier = 2,
		.BlockManagementType = NVM_BLOCK_DATASET,
		.BlockWriteProt = STD_OFF,
		.WriteBlockOnce = STD_OFF,		/* Value is not configurable */
		.SelectBlockForReadall = STD_OFF,
		.SingleBlockCallback = NULL,
		.NvBlockLength = 20,
		.RamBlockDataAddress = NULL,
		.NvBlockNum = 2,
		.NvramDeviceId = 1, 			/* Value is not configurable */		
		.NvBlockBaseNumber = 2,
		.BlockUseCrc = true,
		.CalcRamBlockCrc = false,
		.BlockJobPriority = 0,			/* Value is not configurable */
		.ResistantToChangesSw = FALSE,	/* Value is not configurable */
		.BlockCRCType = NVM_CRC16,
		.RomBlockNum = 0,
		.RomBlockDataAdress = NULL,
		.InitBlockCallback = NULL,
	},
};

const NvM_ConfigType NvM_Config = {
		.Common = {
				.MultiBlockCallback = TEST_MultiBlockCallback,
		},
		.BlockDescriptor = BlockDescriptorList,		
};
