/*
* Configuration of module: Com (Com_PbCfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.5
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Tue May 10 13:57:12 CEST 2011
*/


#include "Com.h"
#include "Com_Internal.h"
#include <stdlib.h>
#if defined(USE_PDUR)
#include "PduR.h"
#endif





/*
 * Signal init values.
 */
const uint16 Com_SignalInitValue_RxPdu1_Signal1 = 0;
const uint16 Com_SignalInitValue_RxPdu2_Signal1 = 0;
const uint16 Com_SignalInitValue_TxPdu1_Signal1 = 0;
const uint16 Com_SignalInitValue_TxPdu2_Signal1 = 0;
const uint8 Com_SignalInitValue_TxPdu2_SignalGroup1_GroupSignal1 = 0;
	

/*
 * Group signal definitions
 */
const ComGroupSignal_type ComGroupSignal[] = {
	{
		.ComHandleId = TxPdu2_SignalGroup1_GroupSignal1,
		.ComBitPosition = 0,
		.ComBitSize = 0,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalInitValue = &Com_SignalInitValue_TxPdu2_SignalGroup1_GroupSignal1,
		.ComSignalType = UINT8,
		.Com_Arc_EOL = 0
	},
	{
		.Com_Arc_EOL = 1
	}
};


/* SignalGroup GroupSignals lists. */
const ComGroupSignal_type * const ComIPduSignalGroupSignalRefs_TxPdu2_SignalGroup1[] = {
	&ComGroupSignal[ TxPdu2_SignalGroup1_GroupSignal1 ],
	NULL
};

/*
 * Signal definitions
 */
const ComSignal_type ComSignal[] = {
	{
		.ComHandleId = RxPdu1_Signal1,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = &Com_SignalInitValue_RxPdu1_Signal1,
		.ComBitPosition = 7,
		.ComBitSize = 16,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT16,
		.Com_Arc_IsSignalGroup = 0,
		.ComGroupSignal = NULL,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.ComHandleId = RxPdu2_Signal1,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = &Com_SignalInitValue_RxPdu2_Signal1,
		.ComBitPosition = 7,
		.ComBitSize = 16,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT16,
		.Com_Arc_IsSignalGroup = 0,
		.ComGroupSignal = NULL,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.ComHandleId = TxPdu1_Signal1,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = &Com_SignalInitValue_TxPdu1_Signal1,
		.ComBitPosition = 7,
		.ComBitSize = 16,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT16,
		.Com_Arc_IsSignalGroup = 0,
		.ComGroupSignal = NULL,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.ComHandleId = TxPdu2_Signal1,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = &Com_SignalInitValue_TxPdu2_Signal1,
		.ComBitPosition = 7,
		.ComBitSize = 16,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT16,
		.Com_Arc_IsSignalGroup = 0,
		.ComGroupSignal = NULL,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.ComHandleId = TxPdu2_SignalGroup1,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComErrorNotification = NULL,
		.ComTransferProperty = PENDING,
		
		.ComUpdateBitPosition = 0,
		.ComSignalArcUseUpdateBit = 0,
		
		
		.ComSignalInitValue = NULL,
		.ComBitPosition = 0,
		.ComBitSize = 0,
		.ComSignalEndianess = COM_BIG_ENDIAN,
		.ComSignalType = UINT8,
		.Com_Arc_IsSignalGroup = 1,
		.ComGroupSignal = ComIPduSignalGroupSignalRefs_TxPdu2_SignalGroup1,
		
		.ComRxDataTimeoutAction = COM_TIMEOUT_DATA_ACTION_NONE,
		.Com_Arc_EOL = 0
	},
	{
		.Com_Arc_EOL = 1
	}
};


/*
 * I-PDU group definitions
 */
const ComIPduGroup_type ComIPduGroup[] = {
	{
		.ComIPduGroupHandleId = ComPduGroup,
		.Com_Arc_EOL = 0
	},
	
	{
		.Com_Arc_EOL  = 1
	}
};

/* IPdu signal lists. */
const ComSignal_type * const ComIPduSignalRefs_RxPdu1[] = {
	&ComSignal[ RxPdu1_Signal1 ],		
	NULL,
};
const ComSignal_type * const ComIPduSignalRefs_RxPdu2[] = {
	&ComSignal[ RxPdu2_Signal1 ],		
	NULL,
};
const ComSignal_type * const ComIPduSignalRefs_TxPdu1[] = {
	&ComSignal[ TxPdu1_Signal1 ],		
	NULL,
};
const ComSignal_type * const ComIPduSignalRefs_TxPdu2[] = {
	&ComSignal[ TxPdu2_Signal1 ],
	&ComSignal[ TxPdu2_SignalGroup1 ],		
	NULL,
};

/*
 * I-PDU definitions
 */
const ComIPdu_type ComIPdu[] = {	
    
	{ // RxPdu1
		.ArcIPduOutgoingId = PDUR_SOURCE_PDU_ID_RxPdu1,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = RECEIVE,
		.ComIPduGroupRef = ComPduGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = NONE,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = ComIPduSignalRefs_RxPdu1,
		.Com_Arc_EOL = 0
	},   
	{ // RxPdu2
		.ArcIPduOutgoingId = PDUR_SOURCE_PDU_ID_RxPdu2,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = RECEIVE,
		.ComIPduGroupRef = ComPduGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = NONE,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = ComIPduSignalRefs_RxPdu2,
		.Com_Arc_EOL = 0
	},   
	{ // TxPdu1
		.ArcIPduOutgoingId = PDUR_DEST_PDU_ID_TxPdu1,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = SEND,
		.ComIPduGroupRef = ComPduGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = DIRECT,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = ComIPduSignalRefs_TxPdu1,
		.Com_Arc_EOL = 0
	},   
	{ // TxPdu2
		.ArcIPduOutgoingId = PDUR_DEST_PDU_ID_TxPdu2,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = SEND,
		.ComIPduGroupRef = ComPduGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = DIRECT,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = ComIPduSignalRefs_TxPdu2,
		.Com_Arc_EOL = 0
	},   
	{
		.Com_Arc_EOL = 1
	}
};

const Com_ConfigType ComConfiguration = {
	.ComConfigurationId = 1,
	.ComIPdu = ComIPdu,
	.ComIPduGroup = ComIPduGroup,
	.ComSignal = ComSignal,
	.ComGroupSignal = ComGroupSignal
};

/* IPdu buffers and signal group buffers */
uint8 ComArcIPduBuffer_RxPdu1[8];
	   
uint8 ComArcIPduBuffer_RxPdu2[8];
	   
uint8 ComArcIPduBuffer_TxPdu1[8];
	   
uint8 ComArcIPduBuffer_TxPdu2[8];
	   
uint8 ComArcSignalGroupBuffer_TxPdu2_SignalGroup1[8];  
	   

Com_Arc_IPdu_type Com_Arc_IPdu[] = {
	{ // RxPdu1
		.Com_Arc_TxIPduTimers = {
			.ComTxIPduNumberOfRepetitionsLeft = 0,
			.ComTxModeRepetitionPeriodTimer = 0,
			.ComTxIPduMinimumDelayTimer = 0,
			.ComTxModeTimePeriodTimer = 0
		},
		.ComIPduDataPtr = ComArcIPduBuffer_RxPdu1,
		.Com_Arc_IpduStarted = 0	
	},
	{ // RxPdu2
		.Com_Arc_TxIPduTimers = {
			.ComTxIPduNumberOfRepetitionsLeft = 0,
			.ComTxModeRepetitionPeriodTimer = 0,
			.ComTxIPduMinimumDelayTimer = 0,
			.ComTxModeTimePeriodTimer = 0
		},
		.ComIPduDataPtr = ComArcIPduBuffer_RxPdu2,
		.Com_Arc_IpduStarted = 0	
	},
	{ // TxPdu1
		.Com_Arc_TxIPduTimers = {
			.ComTxIPduNumberOfRepetitionsLeft = 0,
			.ComTxModeRepetitionPeriodTimer = 0,
			.ComTxIPduMinimumDelayTimer = 0,
			.ComTxModeTimePeriodTimer = 0
		},
		.ComIPduDataPtr = ComArcIPduBuffer_TxPdu1,
		.Com_Arc_IpduStarted = 0	
	},
	{ // TxPdu2
		.Com_Arc_TxIPduTimers = {
			.ComTxIPduNumberOfRepetitionsLeft = 0,
			.ComTxModeRepetitionPeriodTimer = 0,
			.ComTxIPduMinimumDelayTimer = 0,
			.ComTxModeTimePeriodTimer = 0
		},
		.ComIPduDataPtr = ComArcIPduBuffer_TxPdu2,
		.Com_Arc_IpduStarted = 0	
	},
};

Com_Arc_Signal_type Com_Arc_Signal[] = {
	{ // RxPdu1_Signal1
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = NULL
		
	},
	
	{ // RxPdu2_Signal1
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = NULL
		
	},
	
	{ // TxPdu1_Signal1
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = NULL
		
	},
	
	{ // TxPdu2_Signal1
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = NULL
		
	},
	
	{ // TxPdu2_SignalGroup1
		.Com_Arc_DeadlineCounter = 0,
		.ComTimeoutFactor = 0,
		.ComIPduHandleId = 0,
		.ComSignalUpdated = 0,
		.ComIPduDataPtr = NULL,
		
		.Com_Arc_ShadowBuffer = ComArcSignalGroupBuffer_TxPdu2_SignalGroup1
		
	},
	
};

Com_Arc_GroupSignal_type Com_Arc_GroupSignal[COM_N_GROUP_SIGNALS];

uint8 outgoingSduPtr[8];

Com_Arc_Config_type Com_Arc_Config = {
	.ComIPdu = Com_Arc_IPdu,
	.ComSignal = Com_Arc_Signal,
	.ComGroupSignal = Com_Arc_GroupSignal,
	.OutgoingPdu = {
			.SduDataPtr = outgoingSduPtr,
			.SduLength = 0
		}
};

