/*
 * Configuration of module Dio (Dio_Lcfg.c)
 *
 * Created by: 
 * Configured for (MCU): STM32_F107
 *
 * Module vendor: ArcCore
 * Module version: 2.0.0
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Fri Jan 21 11:32:26 CET 2011
 */


	
#include "Dio.h"
#include "Dio_Cfg.h"

const Dio_ChannelType DioChannelConfigData[] = { 
	DIO_CHANNEL_NAME_LED_CHANNEL1,
	DIO_CHANNEL_NAME_LED_CHANNEL2,
	DIO_CHANNEL_NAME_LED_CHANNEL3,
	DIO_CHANNEL_NAME_LED_CHANNEL4,
	DIO_END_OF_LIST
};

const Dio_PortType DioPortConfigData[] = { 
	DIO_PORT_NAME_LED_PORT,  
	DIO_END_OF_LIST
};

const Dio_ChannelGroupType DioConfigData[] = {
	{ 
	  .port = DIO_END_OF_LIST, 
	  .offset = DIO_END_OF_LIST, 
	  .mask = DIO_END_OF_LIST, 
	}
};


uint32 Dio_GetPortConfigSize(void)
{
  return sizeof(DioConfigData);
}
