
EXAMPLENAME=kernel_extra
ROOTDIR?=../../../..
include $(ROOTDIR)/examples/build_example.mk

ifneq (${MAKELEVEL},0) 

# object files
obj-y += system_hooks.o
obj-y += kernel_extra.o

endif	 
	 

