/*
* Configuration of module: Os (Os_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.22
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Wed Mar 16 09:05:04 CET 2011
*/

	

#include <stdlib.h>
#include <stdint.h>
#include "Platform_Types.h"
#include "Os.h"				// includes Os_Cfg.h
#include "os_config_macros.h"
#include "kernel.h"
//#include "isr.h"
//#include "kernel_offset.h"
#include "alist_i.h"
#include "Mcu.h"

// ###############################    EXTERNAL REFERENCES    #############################

/* Application externals */

/* Interrupt externals */ 
void Mcu_LossOfClock ( void );	 
void Mcu_LossOfLock ( void );	 
void OsTick ( void );	


// Set the os tick frequency
OsTickType OsTickFreq = 1000;


// ###############################    DEBUG OUTPUT     #############################
uint32 os_dbg_mask = 0;
 
// ###############################    APPLICATIONS     #############################
GEN_APPLICATION_HEAD = {
	GEN_APPLICATION(
				/* id           */ APPLICATION_ID_OsApplication1,
				/* name         */ "OsApplication1",
				/* trusted      */ true,	/* NOT CONFIGURABLE IN TOOLS */
				0,
				/* StartupHook  */ NULL,	/* Startup Hook */
				/* ShutdownHook */ NULL,	/* Shutdown Hook */
				/* ErrorHook    */ NULL,	/* Error Hook */
				/* rstrtTaskId  */ 0	/* NOT CONFIGURABLE IN TOOLS */
				),					
};
// #################################    COUNTERS     ###############################
GEN_COUNTER_HEAD = {
	GEN_COUNTER(	COUNTER_ID_Counter1,
					"Counter1",
					COUNTER_TYPE_HARD,
					COUNTER_UNIT_NANO,
					0xffff,
					1,
					1,
					0,
					APPLICATION_ID_OsApplication1,	/* Application owner */
					0	/* Accessing application mask */
				),
};

CounterType Os_Arc_OsTickCounter = COUNTER_ID_Counter1;

// ##################################    ALARMS     ################################

GEN_ALARM_HEAD = {
	GEN_ALARM(	ALARM_ID_Alarm1,
				"Alarm1",
				COUNTER_ID_Counter1,
				NULL,
				ALARM_ACTION_ACTIVATETASK,
				TASK_ID_bTask,
				NULL,
				NULL,
				APPLICATION_ID_OsApplication1,	/* Application owner */
				0	/* Accessing application mask */
			),
};

// ################################    RESOURCES     ###############################
GEN_RESOURCE_HEAD = {
	GEN_RESOURCE(
		RES_ID_Resource1,
		RESOURCE_TYPE_STANDARD,
		0,
		APPLICATION_ID_OsApplication1,	/* Application owner */
		0	/* Accessing application mask */
	),
};

// ##############################    STACKS (TASKS)     ############################
DECLARE_STACK(OsIdle,OS_OSIDLE_STACK_SIZE);
DECLARE_STACK(bTask,512);
DECLARE_STACK(eTask1,512);

// ##################################    TASKS     #################################
GEN_TASK_HEAD = {
	GEN_ETASK(	OsIdle,
				"OsIdle",
				0,
				FULL,
				TRUE,
				NULL,
				RES_SCHEDULER,
				0,
				0 
	),
	GEN_BTASK(
		/* 	        		*/bTask,
		/* name        		*/"bTask",
		/* priority    		*/31,
		/* schedule    		*/FULL,
		/* autostart   		*/FALSE,
		/* resource_int_p   */NULL,
		/* resource mask	*/0,
		/* activation lim. 	*/1,
		/* App owner    	*/APPLICATION_ID_OsApplication1,
		/* Accessing apps   */0
	),			
	GEN_ETASK(
		/* 	        		*/eTask1,
		/* name        		*/"eTask1",
		/* priority    		*/1,
		/* schedule 	   	*/FULL,
		/* name        		*/TRUE,
		/* resource_int_p   */NULL,
		/* resource mask	*/0,
		/* App owner    	*/APPLICATION_ID_OsApplication1,
		/* Accessing apps   */0
	),			
};

// ##################################    HOOKS     #################################
GEN_HOOKS( 
	StartupHook, 
	NULL, 
	ShutdownHook, 
	ErrorHook,
	PreTaskHook, 
	PostTaskHook 
);

// ##################################    ISRS     ##################################
GEN_ISR_HEAD = {
	GEN_ISR1(
		/* name      */ "LossOfClock",
		/* vector    */ PLL_SYNSR_LOCF,
		/* priority  */ 5,
		/* entry     */ Mcu_LossOfClock,
		/* appOwner  */ APPLICATION_ID_OsApplication1
	),
	GEN_ISR1(
		/* name      */ "LossOfLock",
		/* vector    */ PLL_SYNSR_LOLF,
		/* priority  */ 5,
		/* entry     */ Mcu_LossOfLock,
		/* appOwner  */ APPLICATION_ID_OsApplication1
	),
	GEN_ISR2(
		/* name      */ "TickTrigg",
		/* vector    */ INTC_SSCIR0_CLR7,
		/* priority  */ 6,
		/* entry     */ OsTick,
		/* appOwner  */ APPLICATION_ID_OsApplication1,
		/* rsrcMask  */ 1
	),
};

GEN_ISR_MAP = {
  [PLL_SYNSR_LOCF] = 0,
  [PLL_SYNSR_LOLF] = 1,
  [INTC_SSCIR0_CLR7] = 2,
};

// ############################    SCHEDULE TABLES     #############################


#include "os_config_funcs.h"
