/*
* Configuration of module: Os (Os_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC551x
*
* Module vendor:           ArcCore
* Generator version:       2.0.34
*
* Generated by Arctic Studio (http://arccore.com) 
*/

	

#include "kernel.h"


// ###############################    EXTERNAL REFERENCES    #############################

/* Application externals */

/* Interrupt externals */


// Set the os tick frequency
OsTickType OsTickFreq = 100;


// ###############################    DEBUG OUTPUT     #############################
uint32 os_dbg_mask = 0;
 
// ###############################    APPLICATIONS     #############################
GEN_APPLICATION_HEAD = {
	GEN_APPLICATION(
				/* id           */ APPLICATION_ID_OsApplication1,
				/* name         */ "OsApplication1",
				/* trusted      */ true,	/* NOT CONFIGURABLE IN TOOLS */
				/* core         */ 0, /* Default value, multicore not enabled.*/
				/* StartupHook  */ NULL,
				/* ShutdownHook */ NULL,
				/* ErrorHook    */ NULL,
				/* rstrtTaskId  */ 0	/* NOT CONFIGURABLE IN TOOLS */
				),					
};
// #################################    COUNTERS     ###############################
GEN_COUNTER_HEAD = {
	GEN_COUNTER(	COUNTER_ID_Counter1,
					"Counter1",
					COUNTER_TYPE_HARD,
					COUNTER_UNIT_NANO,
					0xffff,
					1,
					1,
					0,
					APPLICATION_ID_OsApplication1,	/* Application owner */
					1	/* Accessing application mask */
				),
};

	CounterType Os_Arc_OsTickCounter = COUNTER_ID_Counter1;


// ##################################    ALARMS     ################################

// ################################    RESOURCES     ###############################

// ##############################    STACKS (TASKS)     ############################

DECLARE_STACK(OsIdle,OS_OSIDLE_STACK_SIZE);

DECLARE_STACK(bTask3,2048);
DECLARE_STACK(eTask1,2048);
DECLARE_STACK(eTask2,2048);

// ##################################    TASKS     #################################
GEN_TASK_HEAD = {
	GEN_BTASK(	/* 	        		*/OsIdle,
				/* name        		*/"OsIdle",
				/* priority    		*/0,
				/* schedule    		*/FULL,
				/* autostart   		*/TRUE,
				/* resource_int_p   */NULL,
				/* resource mask	*/0,
				/* activation lim. 	*/1,
				/* App owner    	*/0,
				/* Accessing apps   */1 
	),
	GEN_BTASK(
		/* 	        		*/bTask3,
		/* name        		*/"bTask3",
		/* priority    		*/1,
		/* schedule    		*/FULL,
		/* autostart   		*/FALSE,
		/* resource_int_p   */NULL,
		/* resource mask	*/0,
		/* activation lim. 	*/1,
		/* App owner    	*/APPLICATION_ID_OsApplication1,
		/* Accessing apps   */1
	),			
	GEN_ETASK(
		/* 	        		*/eTask1,
		/* name        		*/"eTask1",
		/* priority    		*/1,
		/* schedule 	   	*/FULL,
		/* name        		*/TRUE,
		/* resource_int_p   */NULL,
		/* resource mask	*/0,
		/* event mask		*/1,
		/* App owner    	*/APPLICATION_ID_OsApplication1,
		/* Accessing apps   */1
	),			
	GEN_ETASK(
		/* 	        		*/eTask2,
		/* name        		*/"eTask2",
		/* priority    		*/1,
		/* schedule 	   	*/FULL,
		/* name        		*/TRUE,
		/* resource_int_p   */NULL,
		/* resource mask	*/0,
		/* event mask		*/1,
		/* App owner    	*/APPLICATION_ID_OsApplication1,
		/* Accessing apps   */1
	),			
};

// ##################################    HOOKS     #################################
GEN_HOOKS( 
	StartupHook, 
	NULL, 
	ShutdownHook, 
	ErrorHook,
	PreTaskHook, 
	PostTaskHook 
);

// ##################################    ISRS     ##################################

GEN_ISR_MAP = {
	0
};

// ############################    SCHEDULE TABLES     #############################

// Table data ScheduleTable_1

GEN_SCHTBL_TASK_LIST_HEAD( 0, 2 ) { 
	TASK_ID_bTask3,
};




GEN_SCHTBL_EVENT_LIST_HEAD( 0, 4 ) {
	{ 
		EVENT_MASK_Event1, 
		TASK_ID_eTask1 
	},
};



GEN_SCHTBL_EVENT_LIST_HEAD( 0, 8 ) {
	{ 
		EVENT_MASK_Event2, 
		TASK_ID_eTask2 
	},
};


GEN_SCHTBL_TASK_LIST_HEAD( 0, 9 ) { 
	TASK_ID_bTask3,
};

GEN_SCHTBL_EVENT_LIST_HEAD( 0, 9 ) {
	{ 
		EVENT_MASK_Event1, 
		TASK_ID_eTask1 
	},
};


GEN_SCHTBL_EXPIRY_POINT_HEAD( 0 ) {
	GEN_SCHTBL_EXPIRY_POINT_W_TASK(0, 2),
	GEN_SCHTBL_EXPIRY_POINT_W_EVENT(0, 4),
	GEN_SCHTBL_EXPIRY_POINT_W_EVENT(0, 8),
	GEN_SCHTBL_EXPIRY_POINT_W_TASK_EVENT(0, 9),
	
};

GEN_SCHTBL_AUTOSTART(
	0,
	SCHTBL_AUTOSTART_ABSOLUTE,
	10, 
	OSDEFAULTAPPMODE
);

// Table heads
GEN_SCHTBL_HEAD = {
	GEN_SCHEDULETABLE(
		0,
		"ScheduleTable_1",
	    COUNTER_ID_Counter1,
	    REPEATING,
		10,
		GEN_SCHTBL_AUTOSTART_NAME(0),
		APPLICATION_ID_OsApplication1,	/* Application owner */
		1	/* Accessing application mask */
	),
};

