/*-------------------------------- Arctic Core ------------------------------
 * Copyright (C) 2013, ArcCore AB, Sweden, www.arccore.com.
 * Contact: <contact@arccore.com>
 *
 * You may ONLY use this file:
 * 1)if you have a valid commercial ArcCore license and then in accordance with
 * the terms contained in the written license agreement between you and ArcCore,
 * or alternatively
 * 2)if you follow the terms found in GNU General Public License version 2 as
 * published by the Free Software Foundation and appearing in the file
 * LICENSE.GPL included in the packaging of this file or here
 * <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>
 *-------------------------------- Arctic Core -----------------------------*/


/* THIS IS A TEMPLATE FILE
 * This file should be generated by the make system. A hash of pre compiled data (e.g.
 * the header files for the modules that supports post build) shall be calculated
 * produce the define below with that hash. This file is included both by the
 * EcuM configuration and the Postbuild configuration. The hashes in EcuM conf. and
 * post build conf. is compared in EcuM and the node will only start if they match.
 */
#define PRE_COMPILED_DATA_HASH_LOW  (0x5555AAAA)
#define PRE_COMPILED_DATA_HASH_HIGH (0x5555AAAA)
