

EXAMPLENAME=rte_simple
ROOTDIR?=../../../..
include $(ROOTDIR)/examples/build_example.mk

ifneq (${MAKELEVEL},0) 

# object files
obj-y += os_simple.o
obj-y += system_hooks.o

endif





