/*
* Configuration of module: PduR (PduR_PbCfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       3.1.10
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#include "PduR.h"


#if PDUR_CANIF_SUPPORT == STD_ON
#include "CanIf.h"
#endif
#if PDUR_CANTP_SUPPORT == STD_ON
#include "CanTp.h"
#endif
#if PDUR_LINIF_SUPPORT == STD_ON
#include "LinIf.h"
#endif
#if PDUR_COM_SUPPORT == STD_ON
#include "Com.h"
#endif
#if PDUR_DCM_SUPPORT == STD_ON
#include "Dcm.h"
#endif
#if PDUR_J1939TP_SUPPORT == STD_ON
#include "J1939Tp.h"
#endif



PduRTpBufferInfo_type PduRTpBuffers[] = {
};

PduRTpBufferInfo_type *PduRTpRouteBufferPtrs[] = {
   NULL
};


		
const PduRDestPdu_type PduRDestination_FreqInd_PduRDestination = {
		.DestModule = ARC_PDUR_CANIF,
		.DestPduId = CANIF_PDU_ID_TX_PDU,
		.DataProvision = PDUR_NO_PROVISION,
		.TxBufferRef = NULL
}; 		
const PduRDestPdu_type PduRDestination_FreqReq_PduRDestination = {
		.DestModule = ARC_PDUR_COM,
		.DestPduId = COM_PDU_ID_FreqReq,
		.DataProvision = PDUR_NO_PROVISION,
		.TxBufferRef = NULL
}; 		
const PduRDestPdu_type PduRDestination_RX_PDU_PduRDestination = {
		.DestModule = ARC_PDUR_COM,
		.DestPduId = COM_PDU_ID_RX_PDU,
		.DataProvision = PDUR_NO_PROVISION,
		.TxBufferRef = NULL
}; 		
const PduRDestPdu_type PduRDestination_TX_PDU_PduRDestination = {
		.DestModule = ARC_PDUR_CANIF,
		.DestPduId = CANIF_PDU_ID_FreqInd,
		.DataProvision = PDUR_NO_PROVISION,
		.TxBufferRef = NULL
}; 

const PduRDestPdu_type * const PduRDestinations_FreqInd[] = {		
	&PduRDestination_FreqInd_PduRDestination,
	NULL
};
const PduRDestPdu_type * const PduRDestinations_FreqReq[] = {		
	&PduRDestination_FreqReq_PduRDestination,
	NULL
};
const PduRDestPdu_type * const PduRDestinations_RX_PDU[] = {		
	&PduRDestination_RX_PDU_PduRDestination,
	NULL
};
const PduRDestPdu_type * const PduRDestinations_TX_PDU[] = {		
	&PduRDestination_TX_PDU_PduRDestination,
	NULL
};


const PduRRoutingPath_type PduRRoutingPath_FreqInd = { 
	.SrcModule = ARC_PDUR_COM,
	.SrcPduId = COM_PDU_ID_TX_PDU,
	.SduLength = 0,
	.PduRDestPdus = PduRDestinations_FreqInd
};	
const PduRRoutingPath_type PduRRoutingPath_FreqReq = { 
	.SrcModule = ARC_PDUR_CANIF,
	.SrcPduId = CANIF_PDU_ID_FreqReq,
	.SduLength = 0,
	.PduRDestPdus = PduRDestinations_FreqReq
};	
const PduRRoutingPath_type PduRRoutingPath_RX_PDU = { 
	.SrcModule = ARC_PDUR_CANIF,
	.SrcPduId = CANIF_PDU_ID_RX_PDU,
	.SduLength = 0,
	.PduRDestPdus = PduRDestinations_RX_PDU
};	
const PduRRoutingPath_type PduRRoutingPath_TX_PDU = { 
	.SrcModule = ARC_PDUR_COM,
	.SrcPduId = COM_PDU_ID_FreqInd,
	.SduLength = 0,
	.PduRDestPdus = PduRDestinations_TX_PDU
};	


const PduRRoutingPath_type * const PduRRoutingPaths[] = { 
	&PduRRoutingPath_FreqInd,
	&PduRRoutingPath_FreqReq,
	&PduRRoutingPath_RX_PDU,
	&PduRRoutingPath_TX_PDU,
	NULL
};


PduR_PBConfigType PduR_Config = {
	.PduRConfigurationId = 0,
	.RoutingPaths = PduRRoutingPaths,
	.TpBuffers = PduRTpBuffers,
	.TpRouteBuffers = PduRTpRouteBufferPtrs,
	.NRoutingPaths = 4
};
