/*
* Configuration of module: Rte (Rte_Logger.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC5567
*
* Module vendor:           ArcCore
* Generator version:       0.0.13
*
* Generated by Arctic Studio (http://arccore.com) 
*/

/* Rte_Logger.h */

#ifndef RTE_LOGGER_H
#define RTE_LOGGER_H

#include "Rte_Type.h"

UInt16 Rte_IRead_LoggerRunnable_Result_result(void);

void LoggerRunnable(void);

#endif
