/*
* Configuration of module: Os (Tasks.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12
*
* Module vendor:           ArcCore
* Generator version:       2.0.34
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Fri Jun 17 16:56:19 CEST 2011
*/

#include "Os.h"
#include "EcuM.h"
#include "Dio.h"
#include "Pwm.h"
#include "Com.h"
#include "CanIf.h"
#include "Adc.h"

// #define USE_LDEBUG_PRINTF // Uncomment this to turn debug statements on.
#include "debug.h"

// Callback when the FreqReq PDU has arrived on COM
void IncommingFreqReq(void)
{
	SetEvent(TASK_ID_ComReceiveTask, EVENT_MASK_FreqReciveEvent);
}

// Tasks
void DipTask( void ) {
	uint16 value = Dio_ReadPort(DIO_PORT_NAME_DipSwitch);
	Dio_WritePort(DIO_PORT_NAME_LEDBar, value);

	// Read from Adc to set the green red intensity
	Adc_ReadGroup(ADC_MAINGROUP, &value);
	value = value*128; // Scale to be between 0 and 32767
	Pwm_SetDutyCycle(GreenLED, value);

	TerminateTask();
}

// Call second stage of startup.
void StartTask()
{
	EcuM_StartupTwo();

	Com_IpduGroupStart(ComPduGroup, false);
	CanIf_SetControllerMode(CANIF_CONTROLLER_ID_CAN0, CANIF_CS_STARTED);

	// Makes the inital value on the bus be correct
	SetEvent(TASK_ID_ComReceiveTask, EVENT_MASK_FreqReciveEvent);

	// Start Group Conversion of ADC
	Adc_StartGroupConversion(ADC_MAINGROUP);
}

// Task that toggles the LED
Dio_LevelType level = 1;
void LedTask( void ) {
	level = !level;
	Dio_WriteChannel(DIO_CHANNEL_NAME_RedLED, level);
	TerminateTask();
}

// Simple task that drives the COM stack.
void ComTask( void ) {
	Com_MainFunctionRx();
	Com_MainFunctionTx();

	TerminateTask();
}

// Task that changes the frequency of the LED when a new
// request is recieved from COM
void ComReceiveTask( void )
{
	uint32 freqreq;

	for(;;)
	{
		WaitEvent(EVENT_MASK_FreqReciveEvent);
		ClearEvent(EVENT_MASK_FreqReciveEvent);

		Com_ReceiveSignal(FreqReqSig, &freqreq);

		CancelAlarm(ALARM_ID_LedAlarm);
		SetRelAlarm(ALARM_ID_LedAlarm, 1, freqreq);

		Com_SendSignal(FreqIndSig, &freqreq);
	}
}

void OsIdle( void ) {
	while(1);
}


// Hooks
#define ERROR_LOG_SIZE 20

struct LogBad_s {
	uint32_t param1;
	uint32_t param2;
	uint32_t param3;
	TaskType taskId;
	OsServiceIdType serviceId;
	StatusType error;
};

void ErrorHook ( StatusType Error ) {

	TaskType task;
	static struct LogBad_s LogBad[ERROR_LOG_SIZE];
	static uint8_t ErrorCount = 0;
	GetTaskID(&task);
	OsServiceIdType service = OSErrorGetServiceId();
	
	LDEBUG_PRINTF("## ErrorHook err=%d\n",Error);

	/* Log the errors in a buffer for later review */
	LogBad[ErrorCount].param1 = os_error.param1;
	LogBad[ErrorCount].param2 = os_error.param2;
	LogBad[ErrorCount].param3 = os_error.param3;
	LogBad[ErrorCount].serviceId = service;
	LogBad[ErrorCount].taskId = task;
	LogBad[ErrorCount].error = Error;

	ErrorCount++;

	// Stall if buffer is full.
	while(ErrorCount >= ERROR_LOG_SIZE);

}

void PostTaskHook ( void ) {
	TaskType task;
	GetTaskID(&task);
	LDEBUG_PRINTF("## PreTaskHook, taskid=%d\n",task);
}

void PreTaskHook ( void ) {
	TaskType task;
	GetTaskID(&task);
	LDEBUG_PRINTF("## PreTaskHook, taskid=%d\n",task);
}

void ShutdownHook ( StatusType Error ) {
	LDEBUG_PRINTF("## ShutdownHook\n");
	while(1);
}

void StartupHook ( void ) {
	LDEBUG_PRINTF("## StartupHook\n");
}
