/*
* Configuration of module: Port (Port_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    STM32_F107
*
* Module vendor:           ArcCore
* Generator version:       null
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((PORT_SW_MAJOR_VERSION == 1) && (PORT_SW_MINOR_VERSION == 0)) )
#error Port: Configuration file expected BSW module version to be 1.0.*
#endif


#ifndef PORT_CFG_H_
#define PORT_CFG_H_

#include "Std_Types.h"
#include "Port_ConfigTypes.h"

#define	PORT_VERSION_INFO_API				STD_OFF
#define	PORT_DEV_ERROR_DETECT				STD_OFF
#define PORT_SET_PIN_DIRECTION_API	        STD_OFF
#define PORT_SET_PIN_MODE_API				STD_OFF
/** Instance of the top level configuration container */
extern const Port_ConfigType PortConfigData;

#endif /* PORT_CFG_H_ */
