/* 
* Configuration of module Com (Com_PbCfg.h)
* 
* Created by: 
* Configured for (MCU): MPC551x
* 
* Module vendor:  ArcCore
* Module version: 1.0.0
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Mon Apr 12 17:47:44 CEST 2010
*/


#if (COM_SW_MAJOR_VERSION != 1) 
#error "Com: Configuration file version differs from BSW version."
#endif

#ifndef COM_PBCFG_H_
#define COM_PBCFG_H_

#include "Com_Types.h"

extern const Com_ConfigType ComConfiguration;

// PDU group definitions
enum {
	RxGroup = 0,
};

// Signal definitions
enum {
	SetLedLevelRx = 0,
};




#endif /* COM_PBCFG_H_ */
