/* 
* Configuration of module EcuC (ComGlobals.h)
* 
* Created by: 
* Configured for (MCU): MPC551x
* 
* Module vendor:  ArcCore
* Module version: 1.0.0
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Mon Apr 12 17:13:20 CEST 2010
*/


#if (ECUC_SW_MAJOR_VERSION != 1) 
#error "EcuC: Configuration file version differs from BSW version."
#endif


#ifndef COMGLOBALS_H_
#define COMGLOBALS_H_

// PDU handle id definitions.
enum {
	LedCommandRx = 0,
};

#endif
