/* 
* Configuration of module EcuM (EcuM_Cfg.h)
* 
* Created by: 
* Configured for (MCU): MPC551x
* 
* Module editor vendor:  ArcCore
* Module editor version: 2.0.0
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Fri Apr 30 15:56:33 CEST 2010
*/


#if (ECUM_SW_MAJOR_VERSION != 1) 
#error "EcuM: Configuration file version differs from BSW version."
#endif



#ifndef ECUM_CFG_H_
#define ECUM_CFG_H_

#define ECUM_VERSION_INFO_API	STD_OFF
#define ECUM_INCLUDE_NVRAM_MGR	STD_OFF
#define ECUM_DEV_ERROR_DETECT	STD_OFF

#include "EcuM_Generated_Types.h"

extern EcuM_ConfigType EcuMConfig;

#endif /*ECUM_CFG_H_*/
