/* 
* Configuration of module Pwm (Pwm_Cfg.c)
* 
* Created by: 
* Configured for (MCU): MPC551x
* 
* Module editor vendor:  ArcCore
* Module editor version: 2.0.0
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Fri Apr 30 15:56:34 CEST 2010
*/

/*
 * Pwm_Cfg.c
 *
 *  Created on: 
 *      Author: 
 */

#include "Pwm.h"
#include "Pwm_Cfg.h"


/*
 * Notification routines are defined elsewhere but need to be linked from here,
 * so we define the routines as external here.
 */

const Pwm_ConfigType PwmConfig = {
	.Channels = {
	
		PWM_CHANNEL_CONFIG(// Channel name and emios channel id
		                   PWM_CHANNEL_1,
		                   // Period in ticks
		                   12000,
		                   // Duty cycle (0 ~> 0%, 0x8000 ~> 100%)
		                   24576,
		                   // Local prescaler
		                   PWM_CHANNEL_PRESCALER_1,
		                   // Polarity
		                   PWM_HIGH),
	},
#if PWM_NOTIFICATION_SUPPORTED==ON
	.NotificationHandlers = {
		// Notification routine for PWM_CHANNEL_1
		,
		
	}
#endif
};
	