/*
* Configuration of module: Ea (Ea_Lcfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    MPC560x
*
* Module vendor:           ArcCore
* Generator version:       2.0.17
*
* Generated by Arctic Studio (http://arccore.com) 
*           on Thu Jun 23 16:26:14 CEST 2011
*/


#warning "This default file may only be used as an example!"

#include "Ea.h"
#include "NvM_Cbk.h"

/*
	ITEM NAME:		<Ea_GeneralData>
	SCOPE:			<Ea Module>
	DESCRIPTION:
		configuration for Ea_General.  
*/
const Ea_GeneralType Ea_GeneralData = {
	0,						/*EaIndex*/
	/** @req EA094  @req EA050  @req EA051  @req EA101 */
	NvM_JobEndNotification,				/*EaNvmJobEndNotification*/
	/** @req EA095  @req EA052  @req EA053  @req EA102 */
	NvM_JobErrorNotification,				/*EaNvmJobEndNotification*/
};

/*
	ITEM NAME:		<Ea_BlockConfigData>
	SCOPE:			<Ea Module>
	DESCRIPTION:
		configuration for Ea_BlockConfig.
		This container mapped EEPROM with block of EA Module
*/

/** @req EA005  @req EA068  @req EA006 */

const Ea_BlockConfigType Ea_BlockConfigData[] = 
/*EaBlockNumber*/ /*EaBlockSize*/ /*EaImmediateData*/ /*EaDeviceIndex*/ /*EaBlockEOL*/
{ 
    {1,   260,   false,   2,   false}, 
    {2,   516,   false,   2,   true},     
};

