/*
 * Configuration of module EcuM (EcuM_Cfg.h)
 *
 * Created by: 
 * Configured for (MCU): MPC5567
 *
 * Module vendor: ArcCore
 * Module version: 2.0.0
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Thu Oct 14 15:29:52 CEST 2010
 */


#warning "This default file may only be used as an example!"

#if (ECUM_SW_MAJOR_VERSION != 1) 
#error "EcuM: Configuration file version differs from BSW version."
#endif



#ifndef ECUM_CFG_H_
#define ECUM_CFG_H_

#define ECUM_VERSION_INFO_API	STD_ON
#define ECUM_INCLUDE_NVRAM_MGR	STD_ON
#define ECUM_DEV_ERROR_DETECT	STD_ON

#include "EcuM_Generated_Types.h"

#define ECUM_MAIN_FUNCTION_PERIOD	200

// EcuM_UserType definitions
typedef enum {
	ECUM_USER_ENDMARK	// Must be the last in list!
} EcuM_UserList;

extern EcuM_ConfigType EcuMConfig;

#endif /*ECUM_CFG_H_*/
