/* 
* Configuration of module EcuM (EcuM_Cfg.c)
* 
* Created by: 
* Configured for (MCU): MPC5567
* 
* Module editor vendor:  ArcCore
* Module editor version: 2.0.0
* 
* 
* Generated by Arctic Studio (http://arccore.com)
*           on Tue May 25 11:41:52 CEST 2010
*/



#warning "This default file may only be used as an example!"

#include "EcuM.h"

EcuM_ConfigType EcuMConfig =
{
	.EcuMDefaultShutdownTarget = ECUM_STATE_RESET,
	.EcuMDefaultShutdownMode = 0, // Don't care
	.EcuMDefaultAppMode = OSDEFAULTAPPMODE,
	.EcuMNvramReadAllTimeout = 10000,
	.EcuMNvramWriteAllTimeout = 10000,
	.EcuMRunSelfRequestPeriod = 10000,

#if defined(USE_MCU)
	.McuConfig = McuConfigData,
#endif
#if defined(USE_PORT)
	.PortConfig = &PortConfigData,
#endif
#if defined(USE_CAN)
	.CanConfig = &CanConfigData,
#endif
#if defined(USE_CANIF)
	.CanIfConfig = &CanIf_Config,
#endif
#if defined(USE_COM)
	.ComConfig = &ComConfiguration,
#endif
#if defined(USE_PDUR)
	.PduRConfig = &PduR_Config,
#endif
#if defined(USE_DMA)
	.DmaConfig = DmaConfig,
#endif
#if defined(USE_ADC)
	.AdcConfig = AdcConfig,
#endif
#if defined(USE_PWM)
	.PwmConfig = &PwmConfig,
#endif
#if defined(USE_GPT)
    .GptConfig = GptConfigData,
#endif
#if defined(USE_FLS)
	.FlashConfig = FlsConfigSet,
#endif

};
