/*
 * Configuration of module Fee (Fee_Cfg.c)
 *
 * Created by: 
 * Configured for (MCU): MPC551x
 *
 * Module vendor: ArcCore
 * Module version: 2.0.2
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Mon Nov 22 09:35:51 CET 2010
 */


#warning "This default file may only be used as an example!"

#include "Fee.h"
#include "NvM_Cbk.h"

const Fee_BlockConfigType BlockConfigList[] = {
};
const Fee_ConfigType Fee_Config = {
		.General = {
				.NvmJobEndCallbackNotificationCallback = NULL,
				.NvmJobErrorCallbackNotificationCallback = NULL,
		},
		.BlockConfig = BlockConfigList,
};
