/*
 * Configuration of module Fee (Fee_Memory_Cfg.h)
 *
 * Created by: 
 * Configured for (MCU): MPC551x
 *
 * Module vendor: ArcCore
 * Module version: 2.0.3
 *
 * 
 * Generated by Arctic Studio (http://arccore.com) 
 *           on Tue Nov 23 14:44:22 CET 2010
 */


#ifndef FEE_MEMORY_CFG_H_
#define FEE_MEMORY_CFG_H_


#define FEE_BANK1_OFFSET			   0x0000
#define FEE_BANK2_OFFSET			   0x4000
#define FEE_BANK1_LENGTH			   0x4000
#define FEE_BANK2_LENGTH			   0x4000

#endif
