/* THIS IS A TEMPLATE FILE
 * This file should be generated by the make system. A hash of pre compiled data (e.g.
 * the header files for the modules that supports post build) shall be calculated
 * produce the define below with that hash. This file is included both by the
 * EcuM configuration and the Postbuild configuration. The hashes in EcuM conf. and
 * post build conf. is compared in EcuM and the node will only start if they match.
 */
#define PRE_COMPILED_DATA_HASH_LOW  (0x5555AAAA)
#define PRE_COMPILED_DATA_HASH_HIGH (0x5555AAAA)
