/* 
* Configuration of module Com (Com_Cfg.h)
* 
* Created by: ArcCore AB
* Configured for (MCU): MPC551x
* 
* Module vendor:  ArcCore
* Module version: 1.0.0
* 
* Copyright ArcCore AB 2010
* Generated by Arctic Studio (http://arccore.com)
*           on Fri Apr 09 13:18:08 CEST 2010
*/


#if (COM_SW_MAJOR_VERSION != 1) 
#error "Com: Configuration file version differs from BSW version."
#endif


#ifndef COM_CFG_H_
#define COM_CFG_H_

#define COM_MODULE_ID 20
#define COM_INSTANCE_ID 1

#define COM_DEV_ERROR_DETECT

#define COM_MAX_NR_IPDU 1
#define COM_MAX_NR_SIGNAL 1
#define COM_MAX_NR_GROUPSIGNAL 0

#define COM_MAX_NR_SIGNALS_PER_IPDU 1
#define COM_MAX_NR_SIGNALGROUPS_PER_IPDU 0
#define COM_MAX_NR_SIGNALS_PER_SIGNAL_GROUP 0

#define COM_E_INVALID_FILTER_CONFIGURATION 101
#define COM_E_INITIALIZATION_FAILED 102
#define COM_E_INVALID_SIGNAL_CONFIGURATION 103
#define COM_INVALID_PDU_ID 104
#define COM_ERROR_SIGNAL_IS_SIGNALGROUP 105

#define COM_E_TOO_MANY_IPDU 106
#define COM_E_TOO_MANY_SIGNAL 107
#define COM_E_TOO_MANY_GROUPSIGNAL 108

#define CPU_ENDIANESS BIG_ENDIAN

/*
 * ComGeneral pre-compile time configuration parameters.
 */
#define ComConfigurationTimeBase 0.0
#define ComVersionInfoApi

#endif /*COM_CFG_H_*/
