/* 
* Configuration of module Com (Com_PbCfg.c)
* 
* Created by: ArcCore AB
* Configured for (MCU): MPC551x
* 
* Module vendor:  ArcCore
* Module version: 1.0.0
* 
* Copyright ArcCore AB 2010
* Generated by Arctic Studio (http://arccore.com)
*           on Fri Apr 09 13:18:08 CEST 2010
*/


#include "Com.h"
#include "stdlib.h"


/*
 * Group signal definitions
 */
const ComGroupSignal_type ComGroupSignal[] = {
	{
		.Com_Arc_EOL = 1
	}
};


/*
 * Signal definitions
 */
const ComSignal_type ComSignal[] = {
	{
		.ComHandleId = SetLedLevelTx,
		.ComFirstTimeoutFactor = 0,
		.ComNotification = NULL,
		.ComTimeoutFactor = 0,
		.ComTimeoutNotification = NULL,
		.ComTransferProperty = TRIGGERED,
		
		
		.ComSignalInitValue = 0,
		.ComBitPosition = 0,
		.ComBitSize = 16,
		.ComSignalEndianess = BIG_ENDIAN,
		.ComSignalType = UINT16,
		
	},
	{
		.Com_Arc_EOL = 1
	}
};


/*
 * I-PDU group definitions
 */
const ComIPduGroup_type ComIPduGroup[] = {
	{
		.ComIPduGroupHandleId = TxGroup
	},
	
	{
		.Com_Arc_EOL  = 1
	}
};


/*
 * I-PDU definitions
 */
const ComIPdu_type ComIPdu[] = {
    
	{
		.ComIPduRxHandleId = LedCommandTx,
		.ComIPduCallout = NULL,
		.ComIPduSignalProcessing =  DEFERRED,
		.ComIPduSize =  8,
		.ComIPduDirection = SEND,
		.ComIPduGroupRef = TxGroup,
		
		.ComTxIPdu = {
			.ComTxIPduMinimumDelayFactor = 0,
			.ComTxIPduUnusedAreasDefault = 0,
			.ComTxModeTrue = {
				.ComTxModeMode = DIRECT,
				.ComTxModeNumberOfRepetitions = 0,
				.ComTxModeRepetitionPeriodFactor = 0,
				.ComTxModeTimeOffsetFactor = 0,
				.ComTxModeTimePeriodFactor = 0,
			},
		},
		
		.ComIPduSignalRef = {
			
			&ComSignal[ SetLedLevelTx ],
					
			NULL,
		},
	},   
	{
		.Com_Arc_EOL = 1
	}
};

const Com_ConfigType ComConfiguration = {
	.ComConfigurationId = 1,
	.ComIPdu = ComIPdu,
	.ComIPduGroup = ComIPduGroup,
	.ComSignal = ComSignal,
	.ComGroupSignal = ComGroupSignal
};


