

#obj-y += xfls_test.o
#obj-y += lin_test.o

#VPATH +=  $(ROOTDIR)/arch/$(ARCH)/delivery/mpc5500_h7f/source
#inc-y +=  $(ROOTDIR)/arch/$(ARCH)/delivery/mpc5500_h7f/include


#linkfile
#ldcmdfile-$(CFG_MPC55XX) = $(ROOTDIR)/arch/$(ARCH)/scripts/linkscript_gcc.ldf

#build-exe-y = ../../../$(target)_$(ARCH).$(TE)


